// +build minimal

#pragma once

#ifndef GO_QTGUI_H
#define GO_QTGUI_H

#include <stdint.h>

#ifdef __cplusplus
int QBitmap_QBitmap_QRegisterMetaType();
int QClipboard_QClipboard_QRegisterMetaType();
int QCloseEvent_QCloseEvent_QRegisterMetaType();
int QContextMenuEvent_QContextMenuEvent_QRegisterMetaType();
int QGuiApplication_QGuiApplication_QRegisterMetaType();
int QHideEvent_QHideEvent_QRegisterMetaType();
int QIconEngine_QIconEngine_QRegisterMetaType();
int QImage_QImage_QRegisterMetaType();
int QInputEvent_QInputEvent_QRegisterMetaType();
int QIntValidator_QIntValidator_QRegisterMetaType();
int QKeyEvent_QKeyEvent_QRegisterMetaType();
int QMouseEvent_QMouseEvent_QRegisterMetaType();
int QPagedPaintDevice_QPagedPaintDevice_QRegisterMetaType();
int QPaintDevice_QPaintDevice_QRegisterMetaType();
int QPaintEngine_QPaintEngine_QRegisterMetaType();
int QPaintEvent_QPaintEvent_QRegisterMetaType();
int QPixmap_QPixmap_QRegisterMetaType();
int QResizeEvent_QResizeEvent_QRegisterMetaType();
int QScreen_QScreen_QRegisterMetaType();
int QShowEvent_QShowEvent_QRegisterMetaType();
int QStandardItem_QStandardItem_QRegisterMetaType();
int QStandardItemModel_QStandardItemModel_QRegisterMetaType();
int QSurface_QSurface_QRegisterMetaType();
int QTextBlockGroup_QTextBlockGroup_QRegisterMetaType();
int QTextDocument_QTextDocument_QRegisterMetaType();
int QTextFrame_QTextFrame_QRegisterMetaType();
int QTextList_QTextList_QRegisterMetaType();
int QTextObject_QTextObject_QRegisterMetaType();
int QTextTable_QTextTable_QRegisterMetaType();
int QValidator_QValidator_QRegisterMetaType();
int QWindow_QWindow_QRegisterMetaType();
extern "C" {
#endif

struct QtGui_PackedString { char* data; long long len; void* ptr; };
struct QtGui_PackedList { void* data; long long len; };
void* QBitmap_NewQBitmap();
void* QBitmap_NewQBitmap2(void* pixmap);
void* QBitmap_NewQBitmap3(int width, int height);
void* QBitmap_NewQBitmap4(void* size);
void* QBitmap_NewQBitmap5(struct QtGui_PackedString fileName, char* format);
void QBitmap_Clear(void* ptr);
void* QBitmap_QBitmap_FromData(void* size, char* bits, long long monoFormat);
void QBitmap_DestroyQBitmap(void* ptr);
void QBitmap_DestroyQBitmapDefault(void* ptr);
void* QBrush_NewQBrush();
void* QBrush_NewQBrush2(long long style);
void* QBrush_NewQBrush3(void* color, long long style);
void* QBrush_NewQBrush4(long long color, long long style);
void* QBrush_NewQBrush5(void* color, void* pixmap);
void* QBrush_NewQBrush6(long long color, void* pixmap);
void* QBrush_NewQBrush7(void* pixmap);
void* QBrush_NewQBrush8(void* image);
void* QBrush_NewQBrush9(void* other);
void* QBrush_NewQBrush10(void* gradient);
void* QBrush_Color(void* ptr);
void QBrush_SetStyle(void* ptr, long long style);
long long QBrush_Style(void* ptr);
void* QBrush_Transform(void* ptr);
void QBrush_DestroyQBrush(void* ptr);
void* QBrush_ToVariant(void* ptr);
void QClipboard_ConnectChanged(void* ptr, long long t);
void QClipboard_DisconnectChanged(void* ptr);
void QClipboard_Changed(void* ptr, long long mode);
void QClipboard_Clear(void* ptr, long long mode);
void* QClipboard_Image(void* ptr, long long mode);
void* QClipboard_Pixmap(void* ptr, long long mode);
void QClipboard_ConnectSelectionChanged(void* ptr, long long t);
void QClipboard_DisconnectSelectionChanged(void* ptr);
void QClipboard_SelectionChanged(void* ptr);
void QClipboard_SetPixmap(void* ptr, void* pixmap, long long mode);
void QClipboard_SetText(void* ptr, struct QtGui_PackedString text, long long mode);
struct QtGui_PackedString QClipboard_Text(void* ptr, long long mode);
struct QtGui_PackedString QClipboard_Text2(void* ptr, struct QtGui_PackedString subtype, long long mode);
void* QClipboard___children_atList(void* ptr, int i);
void QClipboard___children_setList(void* ptr, void* i);
void* QClipboard___children_newList(void* ptr);
void* QClipboard___dynamicPropertyNames_atList(void* ptr, int i);
void QClipboard___dynamicPropertyNames_setList(void* ptr, void* i);
void* QClipboard___dynamicPropertyNames_newList(void* ptr);
void* QClipboard___findChildren_atList(void* ptr, int i);
void QClipboard___findChildren_setList(void* ptr, void* i);
void* QClipboard___findChildren_newList(void* ptr);
void* QClipboard___findChildren_atList3(void* ptr, int i);
void QClipboard___findChildren_setList3(void* ptr, void* i);
void* QClipboard___findChildren_newList3(void* ptr);
void QClipboard_ChildEventDefault(void* ptr, void* event);
void QClipboard_ConnectNotifyDefault(void* ptr, void* sign);
void QClipboard_CustomEventDefault(void* ptr, void* event);
void QClipboard_DeleteLaterDefault(void* ptr);
void QClipboard_DisconnectNotifyDefault(void* ptr, void* sign);
char QClipboard_EventDefault(void* ptr, void* e);
char QClipboard_EventFilterDefault(void* ptr, void* watched, void* event);
void QClipboard_TimerEventDefault(void* ptr, void* event);
void* QCloseEvent_NewQCloseEvent();
void* QColor_NewQColor();
void* QColor_NewQColor2(long long color);
void* QColor_NewQColor3(int r, int g, int b, int a);
void* QColor_NewQColor4(unsigned int color);
void* QColor_NewQColor5(void* rgba64);
void* QColor_NewQColor6(struct QtGui_PackedString name);
void* QColor_NewQColor8(char* name);
void* QColor_NewQColor9(void* name);
int QColor_Alpha(void* ptr);
char QColor_IsValid(void* ptr);
struct QtGui_PackedString QColor_Name(void* ptr);
struct QtGui_PackedString QColor_Name2(void* ptr, long long format);
int QColor_Value(void* ptr);
void* QColor_ToVariant(void* ptr);
void* QContextMenuEvent_NewQContextMenuEvent(long long reason, void* pos, void* globalPos, long long modifiers);
void* QContextMenuEvent_NewQContextMenuEvent2(long long reason, void* pos, void* globalPos);
void* QContextMenuEvent_NewQContextMenuEvent3(long long reason, void* pos);
void* QContextMenuEvent_GlobalPos(void* ptr);
void* QContextMenuEvent_Pos(void* ptr);
int QContextMenuEvent_X(void* ptr);
int QContextMenuEvent_Y(void* ptr);
void* QCursor_NewQCursor();
void* QCursor_NewQCursor2(long long shape);
void* QCursor_NewQCursor3(void* bitmap, void* mask, int hotX, int hotY);
void* QCursor_NewQCursor4(void* pixmap, int hotX, int hotY);
void* QCursor_NewQCursor5(void* c);
void* QCursor_NewQCursor6(void* other);
void* QCursor_Pixmap(void* ptr);
void* QCursor_QCursor_Pos();
void* QCursor_QCursor_Pos2(void* screen);
void QCursor_QCursor_SetPos(int x, int y);
void QCursor_QCursor_SetPos2(void* screen, int x, int y);
void QCursor_QCursor_SetPos3(void* p);
void QCursor_QCursor_SetPos4(void* screen, void* p);
void QCursor_DestroyQCursor(void* ptr);
void* QFont_NewQFont();
void* QFont_NewQFont2(struct QtGui_PackedString family, int pointSize, int weight, char italic);
void* QFont_NewQFont4(void* font, void* pd);
void* QFont_NewQFont5(void* font);
char QFont_Bold(void* ptr);
struct QtGui_PackedString QFont_Family(void* ptr);
char QFont_FromString(void* ptr, struct QtGui_PackedString descrip);
char QFont_Italic(void* ptr);
struct QtGui_PackedString QFont_Key(void* ptr);
int QFont_PointSize(void* ptr);
void QFont_SetFamily(void* ptr, struct QtGui_PackedString family);
void QFont_SetPointSize(void* ptr, int pointSize);
void QFont_SetStretch(void* ptr, int factor);
void QFont_SetStyle(void* ptr, long long style);
void QFont_SetStyleName(void* ptr, struct QtGui_PackedString styleName);
int QFont_Stretch(void* ptr);
char QFont_StrikeOut(void* ptr);
long long QFont_Style(void* ptr);
struct QtGui_PackedString QFont_StyleName(void* ptr);
char QFont_Underline(void* ptr);
int QFont_Weight(void* ptr);
void QFont_DestroyQFont(void* ptr);
void* QFont_ToVariant(void* ptr);
void* QFontMetrics_NewQFontMetrics(void* font);
void* QFontMetrics_NewQFontMetrics3(void* font, void* paintdevice);
void* QFontMetrics_NewQFontMetrics4(void* fm);
void* QFontMetrics_BoundingRect(void* ptr, void* ch);
void* QFontMetrics_BoundingRect2(void* ptr, struct QtGui_PackedString text);
void* QFontMetrics_BoundingRect3(void* ptr, void* rect, int flags, struct QtGui_PackedString text, int tabStops, int tabArray);
void* QFontMetrics_BoundingRect4(void* ptr, int x, int y, int width, int height, int flags, struct QtGui_PackedString text, int tabStops, int tabArray);
int QFontMetrics_Height(void* ptr);
void* QFontMetrics_Size(void* ptr, int flags, struct QtGui_PackedString text, int tabStops, int tabArray);
void QFontMetrics_DestroyQFontMetrics(void* ptr);
void* QGlyphRun_NewQGlyphRun();
void* QGlyphRun_NewQGlyphRun2(void* other);
void* QGlyphRun_BoundingRect(void* ptr);
void QGlyphRun_Clear(void* ptr);
char QGlyphRun_IsEmpty(void* ptr);
char QGlyphRun_StrikeOut(void* ptr);
char QGlyphRun_Underline(void* ptr);
void QGlyphRun_DestroyQGlyphRun(void* ptr);
unsigned int QGlyphRun___glyphIndexes_atList(void* ptr, int i);
void QGlyphRun___glyphIndexes_setList(void* ptr, unsigned int i);
void* QGlyphRun___glyphIndexes_newList(void* ptr);
void* QGlyphRun___positions_atList(void* ptr, int i);
void QGlyphRun___positions_setList(void* ptr, void* i);
void* QGlyphRun___positions_newList(void* ptr);
unsigned int QGlyphRun___setGlyphIndexes_glyphIndexes_atList(void* ptr, int i);
void QGlyphRun___setGlyphIndexes_glyphIndexes_setList(void* ptr, unsigned int i);
void* QGlyphRun___setGlyphIndexes_glyphIndexes_newList(void* ptr);
void* QGlyphRun___setPositions_positions_atList(void* ptr, int i);
void QGlyphRun___setPositions_positions_setList(void* ptr, void* i);
void* QGlyphRun___setPositions_positions_newList(void* ptr);
void* QGradient_NewQGradient2(long long preset);
long long QGradient_Type(void* ptr);
void* QGuiApplication_NewQGuiApplication(int argc, char* argv);
struct QtGui_PackedString QGuiApplication_QGuiApplication_ApplicationDisplayName();
void* QGuiApplication_QGuiApplication_Clipboard();
char QGuiApplication_EventDefault(void* ptr, void* e);
int QGuiApplication_QGuiApplication_Exec();
void* QGuiApplication_QGuiApplication_Font();
void QGuiApplication_QGuiApplication_SetApplicationDisplayName(struct QtGui_PackedString name);
void QGuiApplication_QGuiApplication_SetFont(void* font);
void QGuiApplication_QGuiApplication_SetWindowIcon(void* icon);
void* QGuiApplication_QGuiApplication_WindowIcon();
void QGuiApplication_DestroyQGuiApplication(void* ptr);
void QGuiApplication_DestroyQGuiApplicationDefault(void* ptr);
void* QGuiApplication___screens_atList(void* ptr, int i);
void QGuiApplication___screens_setList(void* ptr, void* i);
void* QGuiApplication___screens_newList(void* ptr);
void* QGuiApplication___children_atList(void* ptr, int i);
void QGuiApplication___children_setList(void* ptr, void* i);
void* QGuiApplication___children_newList(void* ptr);
void* QGuiApplication___dynamicPropertyNames_atList(void* ptr, int i);
void QGuiApplication___dynamicPropertyNames_setList(void* ptr, void* i);
void* QGuiApplication___dynamicPropertyNames_newList(void* ptr);
void* QGuiApplication___findChildren_atList(void* ptr, int i);
void QGuiApplication___findChildren_setList(void* ptr, void* i);
void* QGuiApplication___findChildren_newList(void* ptr);
void* QGuiApplication___findChildren_atList3(void* ptr, int i);
void QGuiApplication___findChildren_setList3(void* ptr, void* i);
void* QGuiApplication___findChildren_newList3(void* ptr);
void QGuiApplication_QuitDefault(void* ptr);
void QGuiApplication_ChildEventDefault(void* ptr, void* event);
void QGuiApplication_ConnectNotifyDefault(void* ptr, void* sign);
void QGuiApplication_CustomEventDefault(void* ptr, void* event);
void QGuiApplication_DeleteLaterDefault(void* ptr);
void QGuiApplication_DisconnectNotifyDefault(void* ptr, void* sign);
char QGuiApplication_EventFilterDefault(void* ptr, void* watched, void* event);
void QGuiApplication_TimerEventDefault(void* ptr, void* event);
void* QHideEvent_NewQHideEvent();
void* QIcon_NewQIcon();
void* QIcon_NewQIcon2(void* pixmap);
void* QIcon_NewQIcon3(void* other);
void* QIcon_NewQIcon4(void* other);
void* QIcon_NewQIcon5(struct QtGui_PackedString fileName);
void* QIcon_NewQIcon6(void* engine);
void* QIcon_QIcon_FromTheme(struct QtGui_PackedString name);
void* QIcon_QIcon_FromTheme2(struct QtGui_PackedString name, void* fallback);
struct QtGui_PackedString QIcon_Name(void* ptr);
void* QIcon_Pixmap(void* ptr, void* size, long long mode, long long state);
void* QIcon_Pixmap2(void* ptr, int w, int h, long long mode, long long state);
void* QIcon_Pixmap3(void* ptr, int extent, long long mode, long long state);
void* QIcon_Pixmap4(void* ptr, void* window, void* size, long long mode, long long state);
void QIcon_DestroyQIcon(void* ptr);
void* QIcon_ToVariant(void* ptr);
void* QIcon___availableSizes_atList(void* ptr, int i);
void QIcon___availableSizes_setList(void* ptr, void* i);
void* QIcon___availableSizes_newList(void* ptr);
void* QIconEngine_NewQIconEngine();
void* QIconEngine_Clone(void* ptr);
struct QtGui_PackedString QIconEngine_Key(void* ptr);
struct QtGui_PackedString QIconEngine_KeyDefault(void* ptr);
void QIconEngine_Paint(void* ptr, void* painter, void* rect, long long mode, long long state);
void* QIconEngine_Pixmap(void* ptr, void* size, long long mode, long long state);
void* QIconEngine_PixmapDefault(void* ptr, void* size, long long mode, long long state);
char QIconEngine_Read(void* ptr, void* in);
char QIconEngine_ReadDefault(void* ptr, void* in);
char QIconEngine_Write(void* ptr, void* out);
char QIconEngine_WriteDefault(void* ptr, void* out);
void QIconEngine_DestroyQIconEngine(void* ptr);
void QIconEngine_DestroyQIconEngineDefault(void* ptr);
void* QIconEngine___availableSizes_atList(void* ptr, int i);
void QIconEngine___availableSizes_setList(void* ptr, void* i);
void* QIconEngine___availableSizes_newList(void* ptr);
void* QImage_NewQImage();
void* QImage_NewQImage2(void* size, long long format);
void* QImage_NewQImage3(int width, int height, long long format);
void* QImage_NewQImage4(char* data, int width, int height, long long format);
void* QImage_NewQImage5(char* data, int width, int height, long long format);
void* QImage_NewQImage6(char* data, int width, int height, int bytesPerLine, long long format);
void* QImage_NewQImage7(char* data, int width, int height, int bytesPerLine, long long format);
void* QImage_NewQImage9(struct QtGui_PackedString fileName, char* format);
void* QImage_NewQImage10(void* image);
void* QImage_NewQImage11(void* other);
unsigned int QImage_Color(void* ptr, int i);
void* QImage_Copy(void* ptr, void* rectangle);
void* QImage_Copy2(void* ptr, int x, int y, int width, int height);
long long QImage_Format(void* ptr);
void* QImage_QImage_FromData(char* data, int size, char* format);
void* QImage_QImage_FromData2(void* data, char* format);
char QImage_Load(void* ptr, struct QtGui_PackedString fileName, char* format);
char QImage_Load2(void* ptr, void* device, char* format);
char QImage_LoadFromData(void* ptr, char* data, int l, char* format);
char QImage_LoadFromData2(void* ptr, void* data, char* format);
void* QImage_Rect(void* ptr);
char QImage_Save(void* ptr, struct QtGui_PackedString fileName, char* format, int quality);
char QImage_Save2(void* ptr, void* device, char* format, int quality);
void* QImage_Scaled(void* ptr, void* size, long long aspectRatioMode, long long transformMode);
void* QImage_Scaled2(void* ptr, int width, int height, long long aspectRatioMode, long long transformMode);
void* QImage_ScaledToHeight(void* ptr, int height, long long mode);
void QImage_SetText(void* ptr, struct QtGui_PackedString key, struct QtGui_PackedString text);
void* QImage_Size(void* ptr);
struct QtGui_PackedString QImage_Text(void* ptr, struct QtGui_PackedString key);
char QImage_Valid(void* ptr, void* pos);
char QImage_Valid2(void* ptr, int x, int y);
void QImage_DestroyQImage(void* ptr);
void QImage_DestroyQImageDefault(void* ptr);
void* QImage_ToVariant(void* ptr);
unsigned int QImage___colorTable_atList(void* ptr, int i);
void QImage___colorTable_setList(void* ptr, unsigned int i);
void* QImage___colorTable_newList(void* ptr);
unsigned int QImage___convertToFormat_colorTable_atList3(void* ptr, int i);
void QImage___convertToFormat_colorTable_setList3(void* ptr, unsigned int i);
void* QImage___convertToFormat_colorTable_newList3(void* ptr);
unsigned int QImage___setColorTable_colors_atList(void* ptr, int i);
void QImage___setColorTable_colors_setList(void* ptr, unsigned int i);
void* QImage___setColorTable_colors_newList(void* ptr);
void* QImage_PaintEngine(void* ptr);
void* QImage_PaintEngineDefault(void* ptr);
void* QIntValidator_NewQIntValidator(void* parent);
void* QIntValidator_NewQIntValidator2(int minimum, int maximum, void* parent);
void QIntValidator_SetRange(void* ptr, int bottom, int top);
void QIntValidator_SetRangeDefault(void* ptr, int bottom, int top);
void QIntValidator_SetTop(void* ptr, int vin);
int QIntValidator_Top(void* ptr);
void QIntValidator_DestroyQIntValidator(void* ptr);
void QIntValidator_DestroyQIntValidatorDefault(void* ptr);
long long QIntValidator_Validate(void* ptr, struct QtGui_PackedString input, int pos);
long long QIntValidator_ValidateDefault(void* ptr, struct QtGui_PackedString input, int pos);
void* QKeyEvent_NewQKeyEvent(long long ty, int key, long long modifiers, struct QtGui_PackedString text, char autorep, unsigned short count);
void* QKeyEvent_NewQKeyEvent2(long long ty, int key, long long modifiers, unsigned int nativeScanCode, unsigned int nativeVirtualKey, unsigned int nativeModifiers, struct QtGui_PackedString text, char autorep, unsigned short count);
int QKeyEvent_Count(void* ptr);
int QKeyEvent_Key(void* ptr);
struct QtGui_PackedString QKeyEvent_Text(void* ptr);
void* QKeySequence_NewQKeySequence();
void* QKeySequence_NewQKeySequence2(struct QtGui_PackedString key, long long format);
void* QKeySequence_NewQKeySequence3(int k1, int k2, int k3, int k4);
void* QKeySequence_NewQKeySequence4(void* keysequence);
void* QKeySequence_NewQKeySequence5(long long key);
int QKeySequence_Count(void* ptr);
void* QKeySequence_QKeySequence_FromString(struct QtGui_PackedString str, long long format);
char QKeySequence_IsEmpty(void* ptr);
void QKeySequence_DestroyQKeySequence(void* ptr);
void* QKeySequence___keyBindings_atList(void* ptr, int i);
void QKeySequence___keyBindings_setList(void* ptr, void* i);
void* QKeySequence___keyBindings_newList(void* ptr);
void* QKeySequence___listFromString_atList(void* ptr, int i);
void QKeySequence___listFromString_setList(void* ptr, void* i);
void* QKeySequence___listFromString_newList(void* ptr);
void* QKeySequence___listToString_list_atList(void* ptr, int i);
void QKeySequence___listToString_list_setList(void* ptr, void* i);
void* QKeySequence___listToString_list_newList(void* ptr);
void* QMatrix4x4_NewQMatrix4x4();
void* QMatrix4x4_NewQMatrix4x43(float values);
void* QMatrix4x4_NewQMatrix4x44(float m11, float m12, float m13, float m14, float m21, float m22, float m23, float m24, float m31, float m32, float m33, float m34, float m41, float m42, float m43, float m44);
void* QMatrix4x4_Column(void* ptr, int index);
float QMatrix4x4_Data(void* ptr);
float QMatrix4x4_Data2(void* ptr);
void* QMatrix4x4_Map(void* ptr, void* point);
void* QMatrix4x4_Map2(void* ptr, void* point);
void* QMatrix4x4_Map3(void* ptr, void* point);
void* QMatrix4x4_Map4(void* ptr, void* point);
void* QMatrix4x4_Row(void* ptr, int index);
void QMatrix4x4_Scale(void* ptr, void* vector);
void QMatrix4x4_Scale2(void* ptr, float x, float y);
void QMatrix4x4_Scale3(void* ptr, float x, float y, float z);
void QMatrix4x4_Scale4(void* ptr, float factor);
void QMatrix4x4_SetColumn(void* ptr, int index, void* value);
void* QMouseEvent_NewQMouseEvent(long long ty, void* localPos, long long button, long long buttons, long long modifiers);
void* QMouseEvent_NewQMouseEvent2(long long ty, void* localPos, void* screenPos, long long button, long long buttons, long long modifiers);
void* QMouseEvent_NewQMouseEvent3(long long ty, void* localPos, void* windowPos, void* screenPos, long long button, long long buttons, long long modifiers);
void* QMouseEvent_NewQMouseEvent4(long long ty, void* localPos, void* windowPos, void* screenPos, long long button, long long buttons, long long modifiers, long long source);
long long QMouseEvent_Button(void* ptr);
long long QMouseEvent_Buttons(void* ptr);
void* QMouseEvent_GlobalPos(void* ptr);
void* QMouseEvent_Pos(void* ptr);
int QMouseEvent_X(void* ptr);
int QMouseEvent_Y(void* ptr);
void* QPageSize_NewQPageSize();
void* QPageSize_NewQPageSize2(long long pageSize);
void* QPageSize_NewQPageSize3(void* pointSize, struct QtGui_PackedString name, long long matchPolicy);
void* QPageSize_NewQPageSize4(void* size, long long units, struct QtGui_PackedString name, long long matchPolicy);
void* QPageSize_NewQPageSize5(void* other);
long long QPageSize_Id(void* ptr);
long long QPageSize_QPageSize_Id2(void* pointSize, long long matchPolicy);
long long QPageSize_QPageSize_Id3(void* size, long long units, long long matchPolicy);
long long QPageSize_QPageSize_Id4(int windowsId);
char QPageSize_IsValid(void* ptr);
struct QtGui_PackedString QPageSize_Key(void* ptr);
struct QtGui_PackedString QPageSize_QPageSize_Key2(long long pageSizeId);
struct QtGui_PackedString QPageSize_Name(void* ptr);
struct QtGui_PackedString QPageSize_QPageSize_Name2(long long pageSizeId);
void* QPageSize_Rect(void* ptr, long long units);
void* QPageSize_Size(void* ptr, long long units);
void* QPageSize_QPageSize_Size2(long long pageSizeId, long long units);
void QPageSize_DestroyQPageSize(void* ptr);
char QPagedPaintDevice_NewPage(void* ptr);
void QPagedPaintDevice_DestroyQPagedPaintDevice(void* ptr);
void QPagedPaintDevice_DestroyQPagedPaintDeviceDefault(void* ptr);
void* QPagedPaintDevice_PaintEngine(void* ptr);
void* QPagedPaintDevice_PaintEngineDefault(void* ptr);
void* QPaintDevice_NewQPaintDevice();
int QPaintDevice_Height(void* ptr);
int QPaintDevice_Metric(void* ptr, long long metric);
int QPaintDevice_MetricDefault(void* ptr, long long metric);
void* QPaintDevice_PaintEngine(void* ptr);
int QPaintDevice_Width(void* ptr);
void QPaintDevice_DestroyQPaintDevice(void* ptr);
void QPaintDevice_DestroyQPaintDeviceDefault(void* ptr);
void* QPaintEngine_NewQPaintEngine(long long caps);
char QPaintEngine_Begin(void* ptr, void* pdev);
void QPaintEngine_DrawPixmap(void* ptr, void* r, void* pm, void* sr);
char QPaintEngine_End(void* ptr);
void QPaintEngine_SetActive(void* ptr, char state);
long long QPaintEngine_Type(void* ptr);
void QPaintEngine_UpdateState(void* ptr, void* state);
void QPaintEngine_DestroyQPaintEngine(void* ptr);
void QPaintEngine_DestroyQPaintEngineDefault(void* ptr);
void* QPaintEngineState_Brush(void* ptr);
void* QPaintEngineState_Font(void* ptr);
void* QPaintEngineState_Transform(void* ptr);
void* QPaintEvent_NewQPaintEvent(void* paintRegion);
void* QPaintEvent_NewQPaintEvent2(void* paintRect);
void* QPaintEvent_Rect(void* ptr);
void* QPainter_NewQPainter();
void* QPainter_NewQPainter2(void* device);
void* QPainter_Background(void* ptr);
char QPainter_Begin(void* ptr, void* device);
void* QPainter_BoundingRect(void* ptr, void* rectangle, int flags, struct QtGui_PackedString text);
void* QPainter_BoundingRect2(void* ptr, void* rectangle, int flags, struct QtGui_PackedString text);
void* QPainter_BoundingRect3(void* ptr, int x, int y, int w, int h, int flags, struct QtGui_PackedString text);
void* QPainter_BoundingRect4(void* ptr, void* rectangle, struct QtGui_PackedString text, void* option);
void* QPainter_Brush(void* ptr);
void* QPainter_Device(void* ptr);
char QPainter_End(void* ptr);
void* QPainter_Font(void* ptr);
void* QPainter_FontMetrics(void* ptr);
void QPainter_Save(void* ptr);
void QPainter_Scale(void* ptr, double sx, double sy);
void QPainter_SetBackground(void* ptr, void* brush);
void QPainter_SetFont(void* ptr, void* font);
void QPainter_SetWindow(void* ptr, void* rectangle);
void QPainter_SetWindow2(void* ptr, int x, int y, int width, int height);
void* QPainter_Transform(void* ptr);
void* QPainter_Window(void* ptr);
void QPainter_DestroyQPainter(void* ptr);
void* QPainter___drawLines_lines_atList2(void* ptr, int i);
void QPainter___drawLines_lines_setList2(void* ptr, void* i);
void* QPainter___drawLines_lines_newList2(void* ptr);
void* QPainter___drawLines_pointPairs_atList4(void* ptr, int i);
void QPainter___drawLines_pointPairs_setList4(void* ptr, void* i);
void* QPainter___drawLines_pointPairs_newList4(void* ptr);
void* QPainter___drawLines_lines_atList6(void* ptr, int i);
void QPainter___drawLines_lines_setList6(void* ptr, void* i);
void* QPainter___drawLines_lines_newList6(void* ptr);
void* QPainter___drawLines_pointPairs_atList8(void* ptr, int i);
void QPainter___drawLines_pointPairs_setList8(void* ptr, void* i);
void* QPainter___drawLines_pointPairs_newList8(void* ptr);
void* QPainter___drawRects_rectangles_atList2(void* ptr, int i);
void QPainter___drawRects_rectangles_setList2(void* ptr, void* i);
void* QPainter___drawRects_rectangles_newList2(void* ptr);
void* QPainter___drawRects_rectangles_atList4(void* ptr, int i);
void QPainter___drawRects_rectangles_setList4(void* ptr, void* i);
void* QPainter___drawRects_rectangles_newList4(void* ptr);
void* QPainterPath_NewQPainterPath();
void* QPainterPath_NewQPainterPath2(void* startPoint);
void* QPainterPath_NewQPainterPath3(void* path);
void* QPainterPath_BoundingRect(void* ptr);
void QPainterPath_Clear(void* ptr);
char QPainterPath_IsEmpty(void* ptr);
double QPainterPath_Length(void* ptr);
void QPainterPath_DestroyQPainterPath(void* ptr);
void* QPainterPath___toFillPolygons_atList(void* ptr, int i);
void QPainterPath___toFillPolygons_setList(void* ptr, void* i);
void* QPainterPath___toFillPolygons_newList(void* ptr);
void* QPainterPath___toFillPolygons_atList2(void* ptr, int i);
void QPainterPath___toFillPolygons_setList2(void* ptr, void* i);
void* QPainterPath___toFillPolygons_newList2(void* ptr);
void* QPainterPath___toSubpathPolygons_atList(void* ptr, int i);
void QPainterPath___toSubpathPolygons_setList(void* ptr, void* i);
void* QPainterPath___toSubpathPolygons_newList(void* ptr);
void* QPainterPath___toSubpathPolygons_atList2(void* ptr, int i);
void QPainterPath___toSubpathPolygons_setList2(void* ptr, void* i);
void* QPainterPath___toSubpathPolygons_newList2(void* ptr);
int QPalette_NColorRoles_Type();
void* QPixmap_NewQPixmap();
void* QPixmap_NewQPixmap2(void* size);
void* QPixmap_NewQPixmap3(struct QtGui_PackedString fileName, char* format, long long flags);
void* QPixmap_NewQPixmap5(void* pixmap);
void* QPixmap_Copy(void* ptr, void* rectangle);
void* QPixmap_Copy2(void* ptr, int x, int y, int width, int height);
char QPixmap_Load(void* ptr, struct QtGui_PackedString fileName, char* format, long long flags);
char QPixmap_LoadFromData(void* ptr, char* data, unsigned int l, char* format, long long flags);
char QPixmap_LoadFromData2(void* ptr, void* data, char* format, long long flags);
void* QPixmap_Rect(void* ptr);
char QPixmap_Save(void* ptr, struct QtGui_PackedString fileName, char* format, int quality);
char QPixmap_Save2(void* ptr, void* device, char* format, int quality);
void* QPixmap_Scaled(void* ptr, void* size, long long aspectRatioMode, long long transformMode);
void* QPixmap_Scaled2(void* ptr, int width, int height, long long aspectRatioMode, long long transformMode);
void* QPixmap_ScaledToHeight(void* ptr, int height, long long mode);
void QPixmap_Scroll(void* ptr, int dx, int dy, int x, int y, int width, int height, void* exposed);
void QPixmap_Scroll2(void* ptr, int dx, int dy, void* rect, void* exposed);
void* QPixmap_Size(void* ptr);
void* QPixmap_ToImage(void* ptr);
void QPixmap_DestroyQPixmap(void* ptr);
void QPixmap_DestroyQPixmapDefault(void* ptr);
void* QPixmap_ToVariant(void* ptr);
void* QPixmap_PaintEngine(void* ptr);
void* QPixmap_PaintEngineDefault(void* ptr);
void* QPolygon_NewQPolygon();
void* QPolygon_NewQPolygon2(int size);
void* QPolygon_NewQPolygon3(void* points);
void* QPolygon_NewQPolygon5(void* rectangle, char closed);
void* QPolygon_BoundingRect(void* ptr);
void QPolygon_Point(void* ptr, int index, int x, int y);
void* QPolygon_Point2(void* ptr, int index);
void QPolygon_SetPoint(void* ptr, int index, int x, int y);
void QPolygon_SetPoint2(void* ptr, int index, void* point);
void QPolygon_DestroyQPolygon(void* ptr);
void* QPolygon___QPolygon_points_atList3(void* ptr, int i);
void QPolygon___QPolygon_points_setList3(void* ptr, void* i);
void* QPolygon___QPolygon_points_newList3(void* ptr);
void* QPolygon___QPolygon_v_atList4(void* ptr, int i);
void QPolygon___QPolygon_v_setList4(void* ptr, void* i);
void* QPolygon___QPolygon_v_newList4(void* ptr);
void* QPolygon___QVector_other_atList4(void* ptr, int i);
void QPolygon___QVector_other_setList4(void* ptr, void* i);
void* QPolygon___QVector_other_newList4(void* ptr);
void* QPolygon___QVector_other_atList5(void* ptr, int i);
void QPolygon___QVector_other_setList5(void* ptr, void* i);
void* QPolygon___QVector_other_newList5(void* ptr);
void* QPolygon___append_value_atList3(void* ptr, int i);
void QPolygon___append_value_setList3(void* ptr, void* i);
void* QPolygon___append_value_newList3(void* ptr);
void* QPolygon___fill_atList(void* ptr, int i);
void QPolygon___fill_setList(void* ptr, void* i);
void* QPolygon___fill_newList(void* ptr);
void* QPolygon___fromList_atList(void* ptr, int i);
void QPolygon___fromList_setList(void* ptr, void* i);
void* QPolygon___fromList_newList(void* ptr);
void* QPolygon___fromList_list_atList(void* ptr, int i);
void QPolygon___fromList_list_setList(void* ptr, void* i);
void* QPolygon___fromList_list_newList(void* ptr);
void* QPolygon___fromStdVector_atList(void* ptr, int i);
void QPolygon___fromStdVector_setList(void* ptr, void* i);
void* QPolygon___fromStdVector_newList(void* ptr);
void* QPolygon___mid_atList(void* ptr, int i);
void QPolygon___mid_setList(void* ptr, void* i);
void* QPolygon___mid_newList(void* ptr);
void* QPolygon___swap_other_atList(void* ptr, int i);
void QPolygon___swap_other_setList(void* ptr, void* i);
void* QPolygon___swap_other_newList(void* ptr);
void* QPolygon___toList_atList(void* ptr, int i);
void QPolygon___toList_setList(void* ptr, void* i);
void* QPolygon___toList_newList(void* ptr);
void* QPolygonF_NewQPolygonF();
void* QPolygonF_NewQPolygonF2(int size);
void* QPolygonF_NewQPolygonF3(void* points);
void* QPolygonF_NewQPolygonF5(void* rectangle);
void* QPolygonF_NewQPolygonF6(void* polygon);
void* QPolygonF_NewQPolygonF7(void* polygon);
void* QPolygonF_BoundingRect(void* ptr);
void QPolygonF_DestroyQPolygonF(void* ptr);
void* QPolygonF___QPolygonF_points_atList3(void* ptr, int i);
void QPolygonF___QPolygonF_points_setList3(void* ptr, void* i);
void* QPolygonF___QPolygonF_points_newList3(void* ptr);
void* QPolygonF___QPolygonF_v_atList4(void* ptr, int i);
void QPolygonF___QPolygonF_v_setList4(void* ptr, void* i);
void* QPolygonF___QPolygonF_v_newList4(void* ptr);
void* QPolygonF___QVector_other_atList4(void* ptr, int i);
void QPolygonF___QVector_other_setList4(void* ptr, void* i);
void* QPolygonF___QVector_other_newList4(void* ptr);
void* QPolygonF___QVector_other_atList5(void* ptr, int i);
void QPolygonF___QVector_other_setList5(void* ptr, void* i);
void* QPolygonF___QVector_other_newList5(void* ptr);
void* QPolygonF___append_value_atList3(void* ptr, int i);
void QPolygonF___append_value_setList3(void* ptr, void* i);
void* QPolygonF___append_value_newList3(void* ptr);
void* QPolygonF___fill_atList(void* ptr, int i);
void QPolygonF___fill_setList(void* ptr, void* i);
void* QPolygonF___fill_newList(void* ptr);
void* QPolygonF___fromList_atList(void* ptr, int i);
void QPolygonF___fromList_setList(void* ptr, void* i);
void* QPolygonF___fromList_newList(void* ptr);
void* QPolygonF___fromList_list_atList(void* ptr, int i);
void QPolygonF___fromList_list_setList(void* ptr, void* i);
void* QPolygonF___fromList_list_newList(void* ptr);
void* QPolygonF___fromStdVector_atList(void* ptr, int i);
void QPolygonF___fromStdVector_setList(void* ptr, void* i);
void* QPolygonF___fromStdVector_newList(void* ptr);
void* QPolygonF___mid_atList(void* ptr, int i);
void QPolygonF___mid_setList(void* ptr, void* i);
void* QPolygonF___mid_newList(void* ptr);
void* QPolygonF___swap_other_atList(void* ptr, int i);
void QPolygonF___swap_other_setList(void* ptr, void* i);
void* QPolygonF___swap_other_newList(void* ptr);
void* QPolygonF___toList_atList(void* ptr, int i);
void QPolygonF___toList_setList(void* ptr, void* i);
void* QPolygonF___toList_newList(void* ptr);
void* QRegion_NewQRegion();
void* QRegion_NewQRegion2(int x, int y, int w, int h, long long t);
void* QRegion_NewQRegion3(void* r, long long t);
void* QRegion_NewQRegion4(void* a, long long fillRule);
void* QRegion_NewQRegion5(void* r);
void* QRegion_NewQRegion6(void* other);
void* QRegion_NewQRegion7(void* bm);
void* QRegion_BoundingRect(void* ptr);
char QRegion_IsEmpty(void* ptr);
void* QRegion___rects_atList(void* ptr, int i);
void QRegion___rects_setList(void* ptr, void* i);
void* QRegion___rects_newList(void* ptr);
void* QResizeEvent_NewQResizeEvent(void* size, void* oldSize);
void* QResizeEvent_Size(void* ptr);
unsigned short QRgba64_Alpha(void* ptr);
void* QScreen_Geometry(void* ptr);
struct QtGui_PackedString QScreen_Model(void* ptr);
struct QtGui_PackedString QScreen_Name(void* ptr);
long long QScreen_Orientation(void* ptr);
void* QScreen_Size(void* ptr);
void QScreen_DestroyQScreen(void* ptr);
void QScreen_DestroyQScreenDefault(void* ptr);
void* QScreen___virtualSiblings_atList(void* ptr, int i);
void QScreen___virtualSiblings_setList(void* ptr, void* i);
void* QScreen___virtualSiblings_newList(void* ptr);
void* QScreen___children_atList(void* ptr, int i);
void QScreen___children_setList(void* ptr, void* i);
void* QScreen___children_newList(void* ptr);
void* QScreen___dynamicPropertyNames_atList(void* ptr, int i);
void QScreen___dynamicPropertyNames_setList(void* ptr, void* i);
void* QScreen___dynamicPropertyNames_newList(void* ptr);
void* QScreen___findChildren_atList(void* ptr, int i);
void QScreen___findChildren_setList(void* ptr, void* i);
void* QScreen___findChildren_newList(void* ptr);
void* QScreen___findChildren_atList3(void* ptr, int i);
void QScreen___findChildren_setList3(void* ptr, void* i);
void* QScreen___findChildren_newList3(void* ptr);
void QScreen_ChildEventDefault(void* ptr, void* event);
void QScreen_ConnectNotifyDefault(void* ptr, void* sign);
void QScreen_CustomEventDefault(void* ptr, void* event);
void QScreen_DeleteLaterDefault(void* ptr);
void QScreen_DisconnectNotifyDefault(void* ptr, void* sign);
char QScreen_EventDefault(void* ptr, void* e);
char QScreen_EventFilterDefault(void* ptr, void* watched, void* event);
void QScreen_TimerEventDefault(void* ptr, void* event);
void* QShowEvent_NewQShowEvent();
void* QStandardItem_NewQStandardItem();
void* QStandardItem_NewQStandardItem2(struct QtGui_PackedString text);
void* QStandardItem_NewQStandardItem3(void* icon, struct QtGui_PackedString text);
void* QStandardItem_NewQStandardItem4(int rows, int columns);
void* QStandardItem_NewQStandardItem5(void* other);
struct QtGui_PackedString QStandardItem_AccessibleDescription(void* ptr);
struct QtGui_PackedString QStandardItem_AccessibleText(void* ptr);
void QStandardItem_AppendColumn(void* ptr, void* items);
void QStandardItem_AppendRow(void* ptr, void* items);
void QStandardItem_AppendRow2(void* ptr, void* item);
void QStandardItem_AppendRows(void* ptr, void* items);
void* QStandardItem_Background(void* ptr);
void* QStandardItem_Child(void* ptr, int row, int column);
int QStandardItem_Column(void* ptr);
int QStandardItem_ColumnCount(void* ptr);
void* QStandardItem_Data(void* ptr, int role);
void* QStandardItem_DataDefault(void* ptr, int role);
void* QStandardItem_Font(void* ptr);
void* QStandardItem_Foreground(void* ptr);
char QStandardItem_HasChildren(void* ptr);
void* QStandardItem_Icon(void* ptr);
void* QStandardItem_Index(void* ptr);
void QStandardItem_InsertColumn(void* ptr, int column, void* items);
void QStandardItem_InsertColumns(void* ptr, int column, int count);
void QStandardItem_InsertRow(void* ptr, int row, void* items);
void QStandardItem_InsertRow2(void* ptr, int row, void* item);
void QStandardItem_InsertRows(void* ptr, int row, void* items);
void QStandardItem_InsertRows2(void* ptr, int row, int count);
void* QStandardItem_Model(void* ptr);
void* QStandardItem_Parent(void* ptr);
void QStandardItem_Read(void* ptr, void* in);
void QStandardItem_ReadDefault(void* ptr, void* in);
void QStandardItem_RemoveColumn(void* ptr, int column);
void QStandardItem_RemoveColumns(void* ptr, int column, int count);
void QStandardItem_RemoveRow(void* ptr, int row);
void QStandardItem_RemoveRows(void* ptr, int row, int count);
int QStandardItem_Row(void* ptr);
int QStandardItem_RowCount(void* ptr);
void QStandardItem_SetAccessibleDescription(void* ptr, struct QtGui_PackedString accessibleDescription);
void QStandardItem_SetAccessibleText(void* ptr, struct QtGui_PackedString accessibleText);
void QStandardItem_SetBackground(void* ptr, void* brush);
void QStandardItem_SetCheckable(void* ptr, char checkable);
void QStandardItem_SetChild(void* ptr, int row, int column, void* item);
void QStandardItem_SetChild2(void* ptr, int row, void* item);
void QStandardItem_SetColumnCount(void* ptr, int columns);
void QStandardItem_SetData(void* ptr, void* value, int role);
void QStandardItem_SetDataDefault(void* ptr, void* value, int role);
void QStandardItem_SetEditable(void* ptr, char editable);
void QStandardItem_SetEnabled(void* ptr, char enabled);
void QStandardItem_SetFont(void* ptr, void* font);
void QStandardItem_SetForeground(void* ptr, void* brush);
void QStandardItem_SetIcon(void* ptr, void* icon);
void QStandardItem_SetText(void* ptr, struct QtGui_PackedString text);
void QStandardItem_SetToolTip(void* ptr, struct QtGui_PackedString toolTip);
void* QStandardItem_SizeHint(void* ptr);
void* QStandardItem_TakeChild(void* ptr, int row, int column);
struct QtGui_PackedString QStandardItem_Text(void* ptr);
struct QtGui_PackedString QStandardItem_ToolTip(void* ptr);
int QStandardItem_Type(void* ptr);
int QStandardItem_TypeDefault(void* ptr);
void QStandardItem_Write(void* ptr, void* out);
void QStandardItem_WriteDefault(void* ptr, void* out);
void QStandardItem_DestroyQStandardItem(void* ptr);
void QStandardItem_DestroyQStandardItemDefault(void* ptr);
void* QStandardItem___appendColumn_items_atList(void* ptr, int i);
void QStandardItem___appendColumn_items_setList(void* ptr, void* i);
void* QStandardItem___appendColumn_items_newList(void* ptr);
void* QStandardItem___appendRow_items_atList(void* ptr, int i);
void QStandardItem___appendRow_items_setList(void* ptr, void* i);
void* QStandardItem___appendRow_items_newList(void* ptr);
void* QStandardItem___appendRows_items_atList(void* ptr, int i);
void QStandardItem___appendRows_items_setList(void* ptr, void* i);
void* QStandardItem___appendRows_items_newList(void* ptr);
void* QStandardItem___insertColumn_items_atList(void* ptr, int i);
void QStandardItem___insertColumn_items_setList(void* ptr, void* i);
void* QStandardItem___insertColumn_items_newList(void* ptr);
void* QStandardItem___insertRow_items_atList(void* ptr, int i);
void QStandardItem___insertRow_items_setList(void* ptr, void* i);
void* QStandardItem___insertRow_items_newList(void* ptr);
void* QStandardItem___insertRows_items_atList(void* ptr, int i);
void QStandardItem___insertRows_items_setList(void* ptr, void* i);
void* QStandardItem___insertRows_items_newList(void* ptr);
void* QStandardItem___takeColumn_atList(void* ptr, int i);
void QStandardItem___takeColumn_setList(void* ptr, void* i);
void* QStandardItem___takeColumn_newList(void* ptr);
void* QStandardItem___takeRow_atList(void* ptr, int i);
void QStandardItem___takeRow_setList(void* ptr, void* i);
void* QStandardItem___takeRow_newList(void* ptr);
void* QStandardItemModel_NewQStandardItemModel(void* parent);
void* QStandardItemModel_NewQStandardItemModel2(int rows, int columns, void* parent);
void QStandardItemModel_AppendColumn(void* ptr, void* items);
void QStandardItemModel_AppendRow(void* ptr, void* items);
void QStandardItemModel_AppendRow2(void* ptr, void* item);
void QStandardItemModel_Clear(void* ptr);
int QStandardItemModel_ColumnCount(void* ptr, void* parent);
int QStandardItemModel_ColumnCountDefault(void* ptr, void* parent);
void* QStandardItemModel_Data(void* ptr, void* index, int role);
void* QStandardItemModel_DataDefault(void* ptr, void* index, int role);
char QStandardItemModel_HasChildrenDefault(void* ptr, void* parent);
void* QStandardItemModel_Index(void* ptr, int row, int column, void* parent);
void* QStandardItemModel_IndexDefault(void* ptr, int row, int column, void* parent);
void QStandardItemModel_InsertColumn(void* ptr, int column, void* items);
char QStandardItemModel_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
void QStandardItemModel_InsertRow(void* ptr, int row, void* items);
void QStandardItemModel_InsertRow2(void* ptr, int row, void* item);
char QStandardItemModel_InsertRowsDefault(void* ptr, int row, int count, void* parent);
void* QStandardItemModel_Item(void* ptr, int row, int column);
void* QStandardItemModel_ItemFromIndex(void* ptr, void* index);
void* QStandardItemModel_Parent(void* ptr, void* child);
void* QStandardItemModel_ParentDefault(void* ptr, void* child);
char QStandardItemModel_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char QStandardItemModel_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
int QStandardItemModel_RowCount(void* ptr, void* parent);
int QStandardItemModel_RowCountDefault(void* ptr, void* parent);
void QStandardItemModel_SetColumnCount(void* ptr, int columns);
char QStandardItemModel_SetDataDefault(void* ptr, void* index, void* value, int role);
void QStandardItemModel_SetHorizontalHeaderLabels(void* ptr, struct QtGui_PackedString labels);
void QStandardItemModel_SetItem(void* ptr, int row, int column, void* item);
void QStandardItemModel_SetItem2(void* ptr, int row, void* item);
void* QStandardItemModel_TakeItem(void* ptr, int row, int column);
void QStandardItemModel_DestroyQStandardItemModel(void* ptr);
void QStandardItemModel_DestroyQStandardItemModelDefault(void* ptr);
void* QStandardItemModel___appendColumn_items_atList(void* ptr, int i);
void QStandardItemModel___appendColumn_items_setList(void* ptr, void* i);
void* QStandardItemModel___appendColumn_items_newList(void* ptr);
void* QStandardItemModel___appendRow_items_atList(void* ptr, int i);
void QStandardItemModel___appendRow_items_setList(void* ptr, void* i);
void* QStandardItemModel___appendRow_items_newList(void* ptr);
void* QStandardItemModel___findItems_atList(void* ptr, int i);
void QStandardItemModel___findItems_setList(void* ptr, void* i);
void* QStandardItemModel___findItems_newList(void* ptr);
void* QStandardItemModel___insertColumn_items_atList(void* ptr, int i);
void QStandardItemModel___insertColumn_items_setList(void* ptr, void* i);
void* QStandardItemModel___insertColumn_items_newList(void* ptr);
void* QStandardItemModel___insertRow_items_atList(void* ptr, int i);
void QStandardItemModel___insertRow_items_setList(void* ptr, void* i);
void* QStandardItemModel___insertRow_items_newList(void* ptr);
void* QStandardItemModel___itemData_atList(void* ptr, int v, int i);
void QStandardItemModel___itemData_setList(void* ptr, int key, void* i);
void* QStandardItemModel___itemData_newList(void* ptr);
struct QtGui_PackedList QStandardItemModel___itemData_keyList(void* ptr);
void* QStandardItemModel___mimeData_indexes_atList(void* ptr, int i);
void QStandardItemModel___mimeData_indexes_setList(void* ptr, void* i);
void* QStandardItemModel___mimeData_indexes_newList(void* ptr);
void* QStandardItemModel___setItemData_roles_atList(void* ptr, int v, int i);
void QStandardItemModel___setItemData_roles_setList(void* ptr, int key, void* i);
void* QStandardItemModel___setItemData_roles_newList(void* ptr);
struct QtGui_PackedList QStandardItemModel___setItemData_roles_keyList(void* ptr);
void* QStandardItemModel___setItemRoleNames_roleNames_atList(void* ptr, int v, int i);
void QStandardItemModel___setItemRoleNames_roleNames_setList(void* ptr, int key, void* i);
void* QStandardItemModel___setItemRoleNames_roleNames_newList(void* ptr);
struct QtGui_PackedList QStandardItemModel___setItemRoleNames_roleNames_keyList(void* ptr);
void* QStandardItemModel___takeColumn_atList(void* ptr, int i);
void QStandardItemModel___takeColumn_setList(void* ptr, void* i);
void* QStandardItemModel___takeColumn_newList(void* ptr);
void* QStandardItemModel___takeRow_atList(void* ptr, int i);
void QStandardItemModel___takeRow_setList(void* ptr, void* i);
void* QStandardItemModel___takeRow_newList(void* ptr);
int QStandardItemModel_____itemData_keyList_atList(void* ptr, int i);
void QStandardItemModel_____itemData_keyList_setList(void* ptr, int i);
void* QStandardItemModel_____itemData_keyList_newList(void* ptr);
int QStandardItemModel_____setItemData_roles_keyList_atList(void* ptr, int i);
void QStandardItemModel_____setItemData_roles_keyList_setList(void* ptr, int i);
void* QStandardItemModel_____setItemData_roles_keyList_newList(void* ptr);
int QStandardItemModel_____setItemRoleNames_roleNames_keyList_atList(void* ptr, int i);
void QStandardItemModel_____setItemRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* QStandardItemModel_____setItemRoleNames_roleNames_keyList_newList(void* ptr);
void* QStandardItemModel___changePersistentIndexList_from_atList(void* ptr, int i);
void QStandardItemModel___changePersistentIndexList_from_setList(void* ptr, void* i);
void* QStandardItemModel___changePersistentIndexList_from_newList(void* ptr);
void* QStandardItemModel___changePersistentIndexList_to_atList(void* ptr, int i);
void QStandardItemModel___changePersistentIndexList_to_setList(void* ptr, void* i);
void* QStandardItemModel___changePersistentIndexList_to_newList(void* ptr);
int QStandardItemModel___dataChanged_roles_atList(void* ptr, int i);
void QStandardItemModel___dataChanged_roles_setList(void* ptr, int i);
void* QStandardItemModel___dataChanged_roles_newList(void* ptr);
void* QStandardItemModel___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void QStandardItemModel___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* QStandardItemModel___layoutAboutToBeChanged_parents_newList(void* ptr);
void* QStandardItemModel___layoutChanged_parents_atList(void* ptr, int i);
void QStandardItemModel___layoutChanged_parents_setList(void* ptr, void* i);
void* QStandardItemModel___layoutChanged_parents_newList(void* ptr);
void* QStandardItemModel___match_atList(void* ptr, int i);
void QStandardItemModel___match_setList(void* ptr, void* i);
void* QStandardItemModel___match_newList(void* ptr);
void* QStandardItemModel___persistentIndexList_atList(void* ptr, int i);
void QStandardItemModel___persistentIndexList_setList(void* ptr, void* i);
void* QStandardItemModel___persistentIndexList_newList(void* ptr);
void* QStandardItemModel___roleNames_atList(void* ptr, int v, int i);
void QStandardItemModel___roleNames_setList(void* ptr, int key, void* i);
void* QStandardItemModel___roleNames_newList(void* ptr);
struct QtGui_PackedList QStandardItemModel___roleNames_keyList(void* ptr);
int QStandardItemModel_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void QStandardItemModel_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* QStandardItemModel_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int QStandardItemModel_____roleNames_keyList_atList(void* ptr, int i);
void QStandardItemModel_____roleNames_keyList_setList(void* ptr, int i);
void* QStandardItemModel_____roleNames_keyList_newList(void* ptr);
int QStandardItemModel_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void QStandardItemModel_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* QStandardItemModel_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* QStandardItemModel___children_atList(void* ptr, int i);
void QStandardItemModel___children_setList(void* ptr, void* i);
void* QStandardItemModel___children_newList(void* ptr);
void* QStandardItemModel___dynamicPropertyNames_atList(void* ptr, int i);
void QStandardItemModel___dynamicPropertyNames_setList(void* ptr, void* i);
void* QStandardItemModel___dynamicPropertyNames_newList(void* ptr);
void* QStandardItemModel___findChildren_atList(void* ptr, int i);
void QStandardItemModel___findChildren_setList(void* ptr, void* i);
void* QStandardItemModel___findChildren_newList(void* ptr);
void* QStandardItemModel___findChildren_atList3(void* ptr, int i);
void QStandardItemModel___findChildren_setList3(void* ptr, void* i);
void* QStandardItemModel___findChildren_newList3(void* ptr);
struct QtGui_PackedList QStandardItemModel_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void QStandardItemModel_ChildEventDefault(void* ptr, void* event);
void QStandardItemModel_ConnectNotifyDefault(void* ptr, void* sign);
void QStandardItemModel_CustomEventDefault(void* ptr, void* event);
void QStandardItemModel_DeleteLaterDefault(void* ptr);
void QStandardItemModel_DisconnectNotifyDefault(void* ptr, void* sign);
char QStandardItemModel_EventDefault(void* ptr, void* e);
char QStandardItemModel_EventFilterDefault(void* ptr, void* watched, void* event);
void QStandardItemModel_TimerEventDefault(void* ptr, void* event);
void* QSurface_Format(void* ptr);
void* QSurface_Size(void* ptr);
long long QSurface_SurfaceType(void* ptr);
void QSurface_DestroyQSurface(void* ptr);
void QSurface_DestroyQSurfaceDefault(void* ptr);
void* QSurfaceFormat_NewQSurfaceFormat();
void* QSurfaceFormat_NewQSurfaceFormat2(long long options);
void* QSurfaceFormat_NewQSurfaceFormat3(void* other);
void QSurfaceFormat_DestroyQSurfaceFormat(void* ptr);
void* QTextBlock_NewQTextBlock3(void* other);
void* QTextBlock_BlockFormat(void* ptr);
void* QTextBlock_CharFormat(void* ptr);
void* QTextBlock_Document(void* ptr);
char QTextBlock_IsValid(void* ptr);
void* QTextBlock_Layout(void* ptr);
int QTextBlock_Length(void* ptr);
void* QTextBlock_Next(void* ptr);
int QTextBlock_Position(void* ptr);
struct QtGui_PackedString QTextBlock_Text(void* ptr);
void* QTextBlock___textFormats_newList(void* ptr);
void* QTextBlockFormat_NewQTextBlockFormat();
long long QTextBlockFormat_Alignment(void* ptr);
int QTextBlockFormat_Indent(void* ptr);
void QTextBlockFormat_SetAlignment(void* ptr, long long alignment);
void QTextBlockFormat_SetIndent(void* ptr, int indentation);
void QTextBlockFormat_SetTopMargin(void* ptr, double margin);
double QTextBlockFormat_TopMargin(void* ptr);
void* QTextBlockFormat___setTabPositions_tabs_newList(void* ptr);
void* QTextBlockFormat___tabPositions_newList(void* ptr);
void* QTextBlockGroup_NewQTextBlockGroup(void* document);
void QTextBlockGroup_DestroyQTextBlockGroup(void* ptr);
void QTextBlockGroup_DestroyQTextBlockGroupDefault(void* ptr);
void* QTextBlockGroup___blockList_atList(void* ptr, int i);
void QTextBlockGroup___blockList_setList(void* ptr, void* i);
void* QTextBlockGroup___blockList_newList(void* ptr);
void* QTextCharFormat_NewQTextCharFormat();
void* QTextCharFormat_Font(void* ptr);
char QTextCharFormat_FontItalic(void* ptr);
double QTextCharFormat_FontPointSize(void* ptr);
char QTextCharFormat_FontStrikeOut(void* ptr);
char QTextCharFormat_FontUnderline(void* ptr);
int QTextCharFormat_FontWeight(void* ptr);
void QTextCharFormat_SetFont(void* ptr, void* font, long long behavior);
void QTextCharFormat_SetFont2(void* ptr, void* font);
void QTextCharFormat_SetFontItalic(void* ptr, char italic);
void QTextCharFormat_SetFontPointSize(void* ptr, double size);
void QTextCharFormat_SetFontStrikeOut(void* ptr, char strikeOut);
void QTextCharFormat_SetFontUnderline(void* ptr, char underline);
void QTextCharFormat_SetFontWeight(void* ptr, int weight);
void QTextCharFormat_SetToolTip(void* ptr, struct QtGui_PackedString text);
struct QtGui_PackedString QTextCharFormat_ToolTip(void* ptr);
void* QTextCursor_NewQTextCursor();
void* QTextCursor_NewQTextCursor2(void* document);
void* QTextCursor_NewQTextCursor3(void* frame);
void* QTextCursor_NewQTextCursor4(void* block);
void* QTextCursor_NewQTextCursor5(void* cursor);
int QTextCursor_Anchor(void* ptr);
void QTextCursor_BeginEditBlock(void* ptr);
void* QTextCursor_Block(void* ptr);
void* QTextCursor_BlockFormat(void* ptr);
void* QTextCursor_CharFormat(void* ptr);
void QTextCursor_ClearSelection(void* ptr);
void* QTextCursor_CreateList(void* ptr, void* format);
void* QTextCursor_CreateList2(void* ptr, long long style);
void* QTextCursor_CurrentList(void* ptr);
void* QTextCursor_Document(void* ptr);
void QTextCursor_EndEditBlock(void* ptr);
char QTextCursor_HasSelection(void* ptr);
void QTextCursor_InsertImage(void* ptr, void* format);
void QTextCursor_InsertImage2(void* ptr, void* format, long long alignment);
void QTextCursor_InsertImage3(void* ptr, struct QtGui_PackedString name);
void QTextCursor_InsertImage4(void* ptr, void* image, struct QtGui_PackedString name);
void* QTextCursor_InsertTable(void* ptr, int rows, int columns, void* format);
void* QTextCursor_InsertTable2(void* ptr, int rows, int columns);
void QTextCursor_InsertText(void* ptr, struct QtGui_PackedString text);
void QTextCursor_InsertText2(void* ptr, struct QtGui_PackedString text, void* format);
void QTextCursor_MergeCharFormat(void* ptr, void* modifier);
int QTextCursor_Position(void* ptr);
void QTextCursor_RemoveSelectedText(void* ptr);
void QTextCursor_Select(void* ptr, long long selection);
struct QtGui_PackedString QTextCursor_SelectedText(void* ptr);
void* QTextCursor_Selection(void* ptr);
int QTextCursor_SelectionEnd(void* ptr);
int QTextCursor_SelectionStart(void* ptr);
void QTextCursor_SetBlockFormat(void* ptr, void* format);
void QTextCursor_SetCharFormat(void* ptr, void* format);
void QTextCursor_SetPosition(void* ptr, int pos, long long m);
void QTextCursor_DestroyQTextCursor(void* ptr);
void* QTextDocument_NewQTextDocument(void* parent);
void* QTextDocument_NewQTextDocument2(struct QtGui_PackedString text, void* parent);
void QTextDocument_AddResource(void* ptr, int ty, void* name, void* resource);
void* QTextDocument_Begin(void* ptr);
void QTextDocument_Clear(void* ptr);
void QTextDocument_ClearDefault(void* ptr);
void* QTextDocument_End(void* ptr);
void* QTextDocument_Find(void* ptr, struct QtGui_PackedString subString, void* cursor, long long options);
void* QTextDocument_Find2(void* ptr, struct QtGui_PackedString subString, int position, long long options);
void* QTextDocument_Find3(void* ptr, void* expr, int from, long long options);
void* QTextDocument_Find4(void* ptr, void* expr, void* cursor, long long options);
void* QTextDocument_Find5(void* ptr, void* expr, int from, long long options);
void* QTextDocument_Find6(void* ptr, void* expr, void* cursor, long long options);
void* QTextDocument_FindBlock(void* ptr, int pos);
void* QTextDocument_FirstBlock(void* ptr);
char QTextDocument_IsEmpty(void* ptr);
char QTextDocument_IsModified(void* ptr);
void* QTextDocument_Object(void* ptr, int objectIndex);
void QTextDocument_Print(void* ptr, void* printer);
void* QTextDocument_Resource(void* ptr, int ty, void* name);
void* QTextDocument_RootFrame(void* ptr);
void QTextDocument_SetHtml(void* ptr, struct QtGui_PackedString html);
void QTextDocument_SetModified(void* ptr, char m);
void QTextDocument_SetModifiedDefault(void* ptr, char m);
void* QTextDocument_Size(void* ptr);
struct QtGui_PackedString QTextDocument_ToHtml(void* ptr, void* encoding);
struct QtGui_PackedString QTextDocument_ToPlainText(void* ptr);
void QTextDocument_DestroyQTextDocument(void* ptr);
void QTextDocument_DestroyQTextDocumentDefault(void* ptr);
void* QTextDocument___allFormats_atList(void* ptr, int i);
void QTextDocument___allFormats_setList(void* ptr, void* i);
void* QTextDocument___allFormats_newList(void* ptr);
void* QTextDocument___children_atList(void* ptr, int i);
void QTextDocument___children_setList(void* ptr, void* i);
void* QTextDocument___children_newList(void* ptr);
void* QTextDocument___dynamicPropertyNames_atList(void* ptr, int i);
void QTextDocument___dynamicPropertyNames_setList(void* ptr, void* i);
void* QTextDocument___dynamicPropertyNames_newList(void* ptr);
void* QTextDocument___findChildren_atList(void* ptr, int i);
void QTextDocument___findChildren_setList(void* ptr, void* i);
void* QTextDocument___findChildren_newList(void* ptr);
void* QTextDocument___findChildren_atList3(void* ptr, int i);
void QTextDocument___findChildren_setList3(void* ptr, void* i);
void* QTextDocument___findChildren_newList3(void* ptr);
void QTextDocument_ChildEventDefault(void* ptr, void* event);
void QTextDocument_ConnectNotifyDefault(void* ptr, void* sign);
void QTextDocument_CustomEventDefault(void* ptr, void* event);
void QTextDocument_DeleteLaterDefault(void* ptr);
void QTextDocument_DisconnectNotifyDefault(void* ptr, void* sign);
char QTextDocument_EventDefault(void* ptr, void* e);
char QTextDocument_EventFilterDefault(void* ptr, void* watched, void* event);
void QTextDocument_TimerEventDefault(void* ptr, void* event);
void* QTextDocumentFragment_NewQTextDocumentFragment();
void* QTextDocumentFragment_NewQTextDocumentFragment2(void* document);
void* QTextDocumentFragment_NewQTextDocumentFragment3(void* cursor);
void* QTextDocumentFragment_NewQTextDocumentFragment4(void* other);
char QTextDocumentFragment_IsEmpty(void* ptr);
struct QtGui_PackedString QTextDocumentFragment_ToHtml(void* ptr, void* encoding);
struct QtGui_PackedString QTextDocumentFragment_ToPlainText(void* ptr);
void QTextDocumentFragment_DestroyQTextDocumentFragment(void* ptr);
void* QTextDocumentWriter_NewQTextDocumentWriter();
void* QTextDocumentWriter_NewQTextDocumentWriter2(void* device, void* format);
void* QTextDocumentWriter_NewQTextDocumentWriter3(struct QtGui_PackedString fileName, void* format);
void* QTextDocumentWriter_Device(void* ptr);
struct QtGui_PackedString QTextDocumentWriter_FileName(void* ptr);
void* QTextDocumentWriter_Format(void* ptr);
char QTextDocumentWriter_Write(void* ptr, void* document);
char QTextDocumentWriter_Write2(void* ptr, void* fragment);
void QTextDocumentWriter_DestroyQTextDocumentWriter(void* ptr);
void* QTextDocumentWriter___supportedDocumentFormats_atList(void* ptr, int i);
void QTextDocumentWriter___supportedDocumentFormats_setList(void* ptr, void* i);
void* QTextDocumentWriter___supportedDocumentFormats_newList(void* ptr);
void* QTextFormat_NewQTextFormat();
void* QTextFormat_NewQTextFormat2(int ty);
void* QTextFormat_NewQTextFormat3(void* other);
void* QTextFormat_Background(void* ptr);
void QTextFormat_ClearBackground(void* ptr);
void QTextFormat_ClearForeground(void* ptr);
void* QTextFormat_Foreground(void* ptr);
char QTextFormat_IsEmpty(void* ptr);
char QTextFormat_IsTableCellFormat(void* ptr);
char QTextFormat_IsTableFormat(void* ptr);
char QTextFormat_IsValid(void* ptr);
void QTextFormat_Merge(void* ptr, void* other);
int QTextFormat_ObjectIndex(void* ptr);
void* QTextFormat_Property(void* ptr, int propertyId);
void QTextFormat_SetBackground(void* ptr, void* brush);
void QTextFormat_SetForeground(void* ptr, void* brush);
void QTextFormat_SetObjectIndex(void* ptr, int index);
int QTextFormat_Type(void* ptr);
void QTextFormat_DestroyQTextFormat(void* ptr);
void* QTextFormat___lengthVectorProperty_atList(void* ptr, int i);
void QTextFormat___lengthVectorProperty_setList(void* ptr, void* i);
void* QTextFormat___lengthVectorProperty_newList(void* ptr);
void* QTextFormat___properties_atList(void* ptr, int v, int i);
void QTextFormat___properties_setList(void* ptr, int key, void* i);
void* QTextFormat___properties_newList(void* ptr);
struct QtGui_PackedList QTextFormat___properties_keyList(void* ptr);
void* QTextFormat___setProperty_value_atList2(void* ptr, int i);
void QTextFormat___setProperty_value_setList2(void* ptr, void* i);
void* QTextFormat___setProperty_value_newList2(void* ptr);
int QTextFormat_____properties_keyList_atList(void* ptr, int i);
void QTextFormat_____properties_keyList_setList(void* ptr, int i);
void* QTextFormat_____properties_keyList_newList(void* ptr);
void* QTextFrame_NewQTextFrame(void* document);
struct QtGui_PackedList QTextFrame_ChildFrames(void* ptr);
void* QTextFrame_FirstCursorPosition(void* ptr);
void* QTextFrame_FrameFormat(void* ptr);
void QTextFrame_DestroyQTextFrame(void* ptr);
void QTextFrame_DestroyQTextFrameDefault(void* ptr);
void* QTextFrame___childFrames_atList(void* ptr, int i);
void QTextFrame___childFrames_setList(void* ptr, void* i);
void* QTextFrame___childFrames_newList(void* ptr);
void* QTextFrameFormat_NewQTextFrameFormat();
double QTextFrameFormat_Border(void* ptr);
void* QTextFrameFormat_BorderBrush(void* ptr);
void* QTextFrameFormat_Height(void* ptr);
double QTextFrameFormat_Margin(void* ptr);
long long QTextFrameFormat_Position(void* ptr);
void QTextFrameFormat_SetBorder(void* ptr, double width);
void QTextFrameFormat_SetBorderBrush(void* ptr, void* brush);
void QTextFrameFormat_SetPosition(void* ptr, long long policy);
void QTextFrameFormat_SetTopMargin(void* ptr, double margin);
double QTextFrameFormat_TopMargin(void* ptr);
void* QTextFrameFormat_Width(void* ptr);
void* QTextImageFormat_NewQTextImageFormat();
double QTextImageFormat_Height(void* ptr);
struct QtGui_PackedString QTextImageFormat_Name(void* ptr);
double QTextImageFormat_Width(void* ptr);
void* QTextLayout_NewQTextLayout();
void* QTextLayout_NewQTextLayout2(struct QtGui_PackedString text);
void* QTextLayout_NewQTextLayout4(struct QtGui_PackedString text, void* font, void* paintdevice);
void* QTextLayout_BoundingRect(void* ptr);
void* QTextLayout_Font(void* ptr);
double QTextLayout_MaximumWidth(void* ptr);
double QTextLayout_MinimumWidth(void* ptr);
void* QTextLayout_Position(void* ptr);
void QTextLayout_SetFont(void* ptr, void* font);
void QTextLayout_SetPosition(void* ptr, void* p);
void QTextLayout_SetText(void* ptr, struct QtGui_PackedString stri);
struct QtGui_PackedString QTextLayout_Text(void* ptr);
void QTextLayout_DestroyQTextLayout(void* ptr);
void* QTextLayout___formats_newList(void* ptr);
void* QTextLayout___glyphRuns_atList(void* ptr, int i);
void QTextLayout___glyphRuns_setList(void* ptr, void* i);
void* QTextLayout___glyphRuns_newList(void* ptr);
void* QTextLength_NewQTextLength();
void* QTextLength_NewQTextLength2(long long ty, double value);
long long QTextLength_Type(void* ptr);
double QTextLength_Value(void* ptr, double maximumLength);
void QTextList_Add(void* ptr, void* block);
int QTextList_Count(void* ptr);
void* QTextList_Format(void* ptr);
void* QTextList_Item(void* ptr, int i);
void QTextList_Remove(void* ptr, void* block);
void* QTextListFormat_NewQTextListFormat();
int QTextListFormat_Indent(void* ptr);
void QTextListFormat_SetIndent(void* ptr, int indentation);
void QTextListFormat_SetStyle(void* ptr, long long style);
long long QTextListFormat_Style(void* ptr);
void* QTextObject_NewQTextObject(void* document);
void* QTextObject_Document(void* ptr);
void* QTextObject_Format(void* ptr);
int QTextObject_ObjectIndex(void* ptr);
void QTextObject_DestroyQTextObject(void* ptr);
void QTextObject_DestroyQTextObjectDefault(void* ptr);
void* QTextObject___children_atList(void* ptr, int i);
void QTextObject___children_setList(void* ptr, void* i);
void* QTextObject___children_newList(void* ptr);
void* QTextObject___dynamicPropertyNames_atList(void* ptr, int i);
void QTextObject___dynamicPropertyNames_setList(void* ptr, void* i);
void* QTextObject___dynamicPropertyNames_newList(void* ptr);
void* QTextObject___findChildren_atList(void* ptr, int i);
void QTextObject___findChildren_setList(void* ptr, void* i);
void* QTextObject___findChildren_newList(void* ptr);
void* QTextObject___findChildren_atList3(void* ptr, int i);
void QTextObject___findChildren_setList3(void* ptr, void* i);
void* QTextObject___findChildren_newList3(void* ptr);
void QTextObject_ChildEventDefault(void* ptr, void* event);
void QTextObject_ConnectNotifyDefault(void* ptr, void* sign);
void QTextObject_CustomEventDefault(void* ptr, void* event);
void QTextObject_DeleteLaterDefault(void* ptr);
void QTextObject_DisconnectNotifyDefault(void* ptr, void* sign);
char QTextObject_EventDefault(void* ptr, void* e);
char QTextObject_EventFilterDefault(void* ptr, void* watched, void* event);
void QTextObject_TimerEventDefault(void* ptr, void* event);
void* QTextOption_NewQTextOption();
void* QTextOption_NewQTextOption2(long long alignment);
void* QTextOption_NewQTextOption3(void* other);
long long QTextOption_Alignment(void* ptr);
void QTextOption_SetAlignment(void* ptr, long long alignment);
void QTextOption_DestroyQTextOption(void* ptr);
double QTextOption___setTabArray_tabStops_atList(void* ptr, int i);
void QTextOption___setTabArray_tabStops_setList(void* ptr, double i);
void* QTextOption___setTabArray_tabStops_newList(void* ptr);
double QTextOption___tabArray_atList(void* ptr, int i);
void QTextOption___tabArray_setList(void* ptr, double i);
void* QTextOption___tabArray_newList(void* ptr);
void QTextTable_AppendColumns(void* ptr, int count);
void QTextTable_AppendRows(void* ptr, int count);
void* QTextTable_CellAt(void* ptr, int row, int column);
void* QTextTable_CellAt2(void* ptr, int position);
void* QTextTable_CellAt3(void* ptr, void* cursor);
int QTextTable_Columns(void* ptr);
void* QTextTable_Format(void* ptr);
void QTextTable_InsertColumns(void* ptr, int index, int columns);
void QTextTable_InsertRows(void* ptr, int index, int rows);
void QTextTable_RemoveColumns(void* ptr, int index, int columns);
void QTextTable_RemoveRows(void* ptr, int index, int rows);
void QTextTable_Resize(void* ptr, int rows, int columns);
int QTextTable_Rows(void* ptr);
void* QTextTableCell_NewQTextTableCell();
void* QTextTableCell_NewQTextTableCell2(void* other);
int QTextTableCell_Column(void* ptr);
void* QTextTableCell_FirstCursorPosition(void* ptr);
void* QTextTableCell_Format(void* ptr);
char QTextTableCell_IsValid(void* ptr);
int QTextTableCell_Row(void* ptr);
void QTextTableCell_DestroyQTextTableCell(void* ptr);
void* QTextTableFormat_NewQTextTableFormat();
long long QTextTableFormat_Alignment(void* ptr);
int QTextTableFormat_Columns(void* ptr);
void QTextTableFormat_SetAlignment(void* ptr, long long alignment);
void* QTextTableFormat___columnWidthConstraints_atList(void* ptr, int i);
void QTextTableFormat___columnWidthConstraints_setList(void* ptr, void* i);
void* QTextTableFormat___columnWidthConstraints_newList(void* ptr);
void* QTextTableFormat___setColumnWidthConstraints_constraints_atList(void* ptr, int i);
void QTextTableFormat___setColumnWidthConstraints_constraints_setList(void* ptr, void* i);
void* QTextTableFormat___setColumnWidthConstraints_constraints_newList(void* ptr);
void* QTransform_NewQTransform2();
void* QTransform_NewQTransform3(double m11, double m12, double m13, double m21, double m22, double m23, double m31, double m32, double m33);
void* QTransform_NewQTransform4(double m11, double m12, double m21, double m22, double dx, double dy);
void QTransform_Map(void* ptr, double x, double y, double tx, double ty);
void* QTransform_Map2(void* ptr, void* point);
void* QTransform_Map3(void* ptr, void* p);
void* QTransform_Map4(void* ptr, void* l);
void* QTransform_Map5(void* ptr, void* line);
void* QTransform_Map6(void* ptr, void* polygon);
void* QTransform_Map7(void* ptr, void* polygon);
void* QTransform_Map8(void* ptr, void* region);
void* QTransform_Map9(void* ptr, void* path);
void QTransform_Map10(void* ptr, int x, int y, int tx, int ty);
void* QTransform_Scale(void* ptr, double sx, double sy);
long long QTransform_Type(void* ptr);
void* QValidator_NewQValidator(void* parent);
void QValidator_ConnectChanged(void* ptr, long long t);
void QValidator_DisconnectChanged(void* ptr);
void QValidator_Changed(void* ptr);
long long QValidator_Validate(void* ptr, struct QtGui_PackedString input, int pos);
void QValidator_DestroyQValidator(void* ptr);
void QValidator_DestroyQValidatorDefault(void* ptr);
void* QValidator___children_atList(void* ptr, int i);
void QValidator___children_setList(void* ptr, void* i);
void* QValidator___children_newList(void* ptr);
void* QValidator___dynamicPropertyNames_atList(void* ptr, int i);
void QValidator___dynamicPropertyNames_setList(void* ptr, void* i);
void* QValidator___dynamicPropertyNames_newList(void* ptr);
void* QValidator___findChildren_atList(void* ptr, int i);
void QValidator___findChildren_setList(void* ptr, void* i);
void* QValidator___findChildren_newList(void* ptr);
void* QValidator___findChildren_atList3(void* ptr, int i);
void QValidator___findChildren_setList3(void* ptr, void* i);
void* QValidator___findChildren_newList3(void* ptr);
void QValidator_ChildEventDefault(void* ptr, void* event);
void QValidator_ConnectNotifyDefault(void* ptr, void* sign);
void QValidator_CustomEventDefault(void* ptr, void* event);
void QValidator_DeleteLaterDefault(void* ptr);
void QValidator_DisconnectNotifyDefault(void* ptr, void* sign);
char QValidator_EventDefault(void* ptr, void* e);
char QValidator_EventFilterDefault(void* ptr, void* watched, void* event);
void QValidator_TimerEventDefault(void* ptr, void* event);
void* QVector2D_NewQVector2D();
void* QVector2D_NewQVector2D3(float xpos, float ypos);
void* QVector2D_NewQVector2D4(void* point);
void* QVector2D_NewQVector2D5(void* point);
void* QVector2D_NewQVector2D6(void* vector);
void* QVector2D_NewQVector2D7(void* vector);
float QVector2D_Length(void* ptr);
float QVector2D_X(void* ptr);
float QVector2D_Y(void* ptr);
void* QVector3D_NewQVector3D();
void* QVector3D_NewQVector3D3(float xpos, float ypos, float zpos);
void* QVector3D_NewQVector3D4(void* point);
void* QVector3D_NewQVector3D5(void* point);
void* QVector3D_NewQVector3D6(void* vector);
void* QVector3D_NewQVector3D7(void* vector, float zpos);
void* QVector3D_NewQVector3D8(void* vector);
float QVector3D_Length(void* ptr);
void* QVector3D_QVector3D_Normal(void* v1, void* v2);
void* QVector3D_QVector3D_Normal2(void* v1, void* v2, void* v3);
float QVector3D_X(void* ptr);
float QVector3D_Y(void* ptr);
float QVector3D_Z(void* ptr);
void* QVector4D_NewQVector4D();
void* QVector4D_NewQVector4D3(float xpos, float ypos, float zpos, float wpos);
void* QVector4D_NewQVector4D4(void* point);
void* QVector4D_NewQVector4D5(void* point);
void* QVector4D_NewQVector4D6(void* vector);
void* QVector4D_NewQVector4D7(void* vector, float zpos, float wpos);
void* QVector4D_NewQVector4D8(void* vector);
void* QVector4D_NewQVector4D9(void* vector, float wpos);
float QVector4D_Length(void* ptr);
void QVector4D_SetW(void* ptr, float w);
float QVector4D_W(void* ptr);
float QVector4D_X(void* ptr);
float QVector4D_Y(void* ptr);
float QVector4D_Z(void* ptr);
void* QWindow_NewQWindow(void* targetScreen);
void* QWindow_NewQWindow2(void* parent);
char QWindow_Close(void* ptr);
char QWindow_CloseDefault(void* ptr);
void QWindow_Create(void* ptr);
void* QWindow_Cursor(void* ptr);
void QWindow_Destroy(void* ptr);
char QWindow_Event(void* ptr, void* ev);
char QWindow_EventDefault(void* ptr, void* ev);
void* QWindow_Format(void* ptr);
void* QWindow_FormatDefault(void* ptr);
void* QWindow_Geometry(void* ptr);
int QWindow_Height(void* ptr);
void QWindow_Hide(void* ptr);
void QWindow_HideDefault(void* ptr);
void QWindow_HideEvent(void* ptr, void* ev);
void QWindow_HideEventDefault(void* ptr, void* ev);
void* QWindow_Icon(void* ptr);
void QWindow_KeyPressEvent(void* ptr, void* ev);
void QWindow_KeyPressEventDefault(void* ptr, void* ev);
void QWindow_KeyReleaseEvent(void* ptr, void* ev);
void QWindow_KeyReleaseEventDefault(void* ptr, void* ev);
void QWindow_Lower(void* ptr);
void QWindow_LowerDefault(void* ptr);
void* QWindow_MaximumSize(void* ptr);
int QWindow_MaximumWidth(void* ptr);
int QWindow_MinimumHeight(void* ptr);
void* QWindow_MinimumSize(void* ptr);
int QWindow_MinimumWidth(void* ptr);
void QWindow_MouseDoubleClickEvent(void* ptr, void* ev);
void QWindow_MouseDoubleClickEventDefault(void* ptr, void* ev);
void QWindow_MousePressEvent(void* ptr, void* ev);
void QWindow_MousePressEventDefault(void* ptr, void* ev);
void QWindow_MouseReleaseEvent(void* ptr, void* ev);
void QWindow_MouseReleaseEventDefault(void* ptr, void* ev);
void* QWindow_Parent(void* ptr, long long mode);
void* QWindow_Parent2(void* ptr);
void* QWindow_Position(void* ptr);
void QWindow_Resize(void* ptr, void* newSize);
void QWindow_Resize2(void* ptr, int w, int h);
void QWindow_ResizeEvent(void* ptr, void* ev);
void QWindow_ResizeEventDefault(void* ptr, void* ev);
void QWindow_SetGeometry(void* ptr, int posx, int posy, int w, int h);
void QWindow_SetGeometryDefault(void* ptr, int posx, int posy, int w, int h);
void QWindow_SetGeometry2(void* ptr, void* rect);
void QWindow_SetGeometry2Default(void* ptr, void* rect);
void QWindow_SetIcon(void* ptr, void* icon);
void QWindow_SetMaximumWidth(void* ptr, int w);
void QWindow_SetMaximumWidthDefault(void* ptr, int w);
void QWindow_SetMinimumSize(void* ptr, void* size);
void QWindow_SetMinimumWidth(void* ptr, int w);
void QWindow_SetMinimumWidthDefault(void* ptr, int w);
void QWindow_SetPosition(void* ptr, void* pt);
void QWindow_SetPosition2(void* ptr, int posx, int posy);
void QWindow_Show(void* ptr);
void QWindow_ShowDefault(void* ptr);
void QWindow_ShowEvent(void* ptr, void* ev);
void QWindow_ShowEventDefault(void* ptr, void* ev);
void QWindow_ShowMaximized(void* ptr);
void QWindow_ShowMaximizedDefault(void* ptr);
void* QWindow_Size(void* ptr);
void* QWindow_SizeDefault(void* ptr);
struct QtGui_PackedString QWindow_Title(void* ptr);
long long QWindow_Type(void* ptr);
int QWindow_Width(void* ptr);
int QWindow_X(void* ptr);
int QWindow_Y(void* ptr);
void QWindow_DestroyQWindow(void* ptr);
void QWindow_DestroyQWindowDefault(void* ptr);
void* QWindow___children_atList(void* ptr, int i);
void QWindow___children_setList(void* ptr, void* i);
void* QWindow___children_newList(void* ptr);
void* QWindow___dynamicPropertyNames_atList(void* ptr, int i);
void QWindow___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWindow___dynamicPropertyNames_newList(void* ptr);
void* QWindow___findChildren_atList(void* ptr, int i);
void QWindow___findChildren_setList(void* ptr, void* i);
void* QWindow___findChildren_newList(void* ptr);
void* QWindow___findChildren_atList3(void* ptr, int i);
void QWindow___findChildren_setList3(void* ptr, void* i);
void* QWindow___findChildren_newList3(void* ptr);
void QWindow_ChildEvent(void* ptr, void* event);
void QWindow_ChildEventDefault(void* ptr, void* event);
void QWindow_ConnectNotify(void* ptr, void* sign);
void QWindow_ConnectNotifyDefault(void* ptr, void* sign);
void QWindow_CustomEvent(void* ptr, void* event);
void QWindow_CustomEventDefault(void* ptr, void* event);
void QWindow_DeleteLater(void* ptr);
void QWindow_DeleteLaterDefault(void* ptr);
void QWindow_DisconnectNotify(void* ptr, void* sign);
void QWindow_DisconnectNotifyDefault(void* ptr, void* sign);
char QWindow_EventFilter(void* ptr, void* watched, void* event);
char QWindow_EventFilterDefault(void* ptr, void* watched, void* event);
void QWindow_TimerEvent(void* ptr, void* event);
void QWindow_TimerEventDefault(void* ptr, void* event);
long long QWindow_SurfaceType(void* ptr);
long long QWindow_SurfaceTypeDefault(void* ptr);

#ifdef __cplusplus
}
#endif

#endif