// +build minimal

#pragma once

#ifndef GO_QTWIDGETS_H
#define GO_QTWIDGETS_H

#include <stdint.h>

#ifdef __cplusplus
int QAbstractButton_QAbstractButton_QRegisterMetaType();
int QAbstractItemView_QAbstractItemView_QRegisterMetaType();
int QAbstractScrollArea_QAbstractScrollArea_QRegisterMetaType();
int QAbstractSlider_QAbstractSlider_QRegisterMetaType();
int QAction_QAction_QRegisterMetaType();
int QApplication_QApplication_QRegisterMetaType();
int QBoxLayout_QBoxLayout_QRegisterMetaType();
int QButtonGroup_QButtonGroup_QRegisterMetaType();
int QColorDialog_QColorDialog_QRegisterMetaType();
int QComboBox_QComboBox_QRegisterMetaType();
int QDial_QDial_QRegisterMetaType();
int QDialog_QDialog_QRegisterMetaType();
int QDockWidget_QDockWidget_QRegisterMetaType();
int QFileDialog_QFileDialog_QRegisterMetaType();
int QFontDialog_QFontDialog_QRegisterMetaType();
int QFrame_QFrame_QRegisterMetaType();
int QGraphicsItem_QGraphicsItem_QRegisterMetaType();
int QGraphicsItemGroup_QGraphicsItemGroup_QRegisterMetaType();
int QGraphicsLayout_QGraphicsLayout_QRegisterMetaType();
int QGraphicsLayoutItem_QGraphicsLayoutItem_QRegisterMetaType();
int QGraphicsObject_QGraphicsObject_QRegisterMetaType();
int QGraphicsSceneContextMenuEvent_QGraphicsSceneContextMenuEvent_QRegisterMetaType();
int QGraphicsSceneEvent_QGraphicsSceneEvent_QRegisterMetaType();
int QGraphicsSceneMouseEvent_QGraphicsSceneMouseEvent_QRegisterMetaType();
int QGraphicsSceneResizeEvent_QGraphicsSceneResizeEvent_QRegisterMetaType();
int QGraphicsTransform_QGraphicsTransform_QRegisterMetaType();
int QGraphicsWidget_QGraphicsWidget_QRegisterMetaType();
int QGridLayout_QGridLayout_QRegisterMetaType();
int QHBoxLayout_QHBoxLayout_QRegisterMetaType();
int QHeaderView_QHeaderView_QRegisterMetaType();
int QInputDialog_QInputDialog_QRegisterMetaType();
int QLabel_QLabel_QRegisterMetaType();
int QLayout_QLayout_QRegisterMetaType();
int QLayoutItem_QLayoutItem_QRegisterMetaType();
int QLineEdit_QLineEdit_QRegisterMetaType();
int QMainWindow_QMainWindow_QRegisterMetaType();
int QMenu_QMenu_QRegisterMetaType();
int QMenuBar_QMenuBar_QRegisterMetaType();
int QMessageBox_QMessageBox_QRegisterMetaType();
int QPushButton_QPushButton_QRegisterMetaType();
int QScrollArea_QScrollArea_QRegisterMetaType();
int QScrollBar_QScrollBar_QRegisterMetaType();
int QSpacerItem_QSpacerItem_QRegisterMetaType();
int QSplitter_QSplitter_QRegisterMetaType();
int QStatusBar_QStatusBar_QRegisterMetaType();
int QStyle_QStyle_QRegisterMetaType();
int QTextEdit_QTextEdit_QRegisterMetaType();
int QToolBar_QToolBar_QRegisterMetaType();
int QTreeView_QTreeView_QRegisterMetaType();
int QVBoxLayout_QVBoxLayout_QRegisterMetaType();
int QWidget_QWidget_QRegisterMetaType();
extern "C" {
#endif

struct QtWidgets_PackedString { char* data; long long len; void* ptr; };
struct QtWidgets_PackedList { void* data; long long len; };
void* QAbstractButton_NewQAbstractButton(void* parent);
void QAbstractButton_Click(void* ptr);
void QAbstractButton_ClickDefault(void* ptr);
void QAbstractButton_ConnectClicked(void* ptr, long long t);
void QAbstractButton_DisconnectClicked(void* ptr);
void QAbstractButton_Clicked(void* ptr, char checked);
void* QAbstractButton_Group(void* ptr);
void* QAbstractButton_Icon(void* ptr);
char QAbstractButton_IsChecked(void* ptr);
void QAbstractButton_PaintEvent(void* ptr, void* e);
void QAbstractButton_SetCheckable(void* ptr, char vbo);
void QAbstractButton_SetChecked(void* ptr, char vbo);
void QAbstractButton_SetCheckedDefault(void* ptr, char vbo);
void QAbstractButton_SetIcon(void* ptr, void* icon);
void QAbstractButton_SetShortcut(void* ptr, void* key);
void QAbstractButton_SetText(void* ptr, struct QtWidgets_PackedString text);
void* QAbstractButton_Shortcut(void* ptr);
struct QtWidgets_PackedString QAbstractButton_Text(void* ptr);
void QAbstractButton_DestroyQAbstractButton(void* ptr);
void QAbstractButton_DestroyQAbstractButtonDefault(void* ptr);
void* QAbstractItemView_NewQAbstractItemView(void* parent);
void QAbstractItemView_ConnectActivated(void* ptr, long long t);
void QAbstractItemView_DisconnectActivated(void* ptr);
void QAbstractItemView_Activated(void* ptr, void* index);
void QAbstractItemView_ClearSelection(void* ptr);
void QAbstractItemView_ClearSelectionDefault(void* ptr);
void QAbstractItemView_ConnectClicked(void* ptr, long long t);
void QAbstractItemView_DisconnectClicked(void* ptr);
void QAbstractItemView_Clicked(void* ptr, void* index);
void* QAbstractItemView_CurrentIndex(void* ptr);
void QAbstractItemView_Edit(void* ptr, void* index);
void QAbstractItemView_EditDefault(void* ptr, void* index);
char QAbstractItemView_Edit2(void* ptr, void* index, long long trigger, void* event);
char QAbstractItemView_Edit2Default(void* ptr, void* index, long long trigger, void* event);
int QAbstractItemView_HorizontalOffset(void* ptr);
void* QAbstractItemView_IndexAt(void* ptr, void* point);
char QAbstractItemView_IsIndexHidden(void* ptr, void* index);
void* QAbstractItemView_Model(void* ptr);
void* QAbstractItemView_MoveCursor(void* ptr, long long cursorAction, long long modifiers);
void* QAbstractItemView_RootIndex(void* ptr);
void QAbstractItemView_ScrollTo(void* ptr, void* index, long long hint);
void QAbstractItemView_SelectionChanged(void* ptr, void* selected, void* deselected);
void QAbstractItemView_SelectionChangedDefault(void* ptr, void* selected, void* deselected);
long long QAbstractItemView_SelectionMode(void* ptr);
void QAbstractItemView_SetAutoScroll(void* ptr, char enable);
void QAbstractItemView_SetCurrentIndex(void* ptr, void* index);
void QAbstractItemView_SetCurrentIndexDefault(void* ptr, void* index);
void QAbstractItemView_SetModel(void* ptr, void* model);
void QAbstractItemView_SetModelDefault(void* ptr, void* model);
void QAbstractItemView_SetSelection(void* ptr, void* rect, long long flags);
void QAbstractItemView_SetSelectionMode(void* ptr, long long mode);
void QAbstractItemView_Update(void* ptr, void* index);
void QAbstractItemView_UpdateDefault(void* ptr, void* index);
int QAbstractItemView_VerticalOffset(void* ptr);
void* QAbstractItemView_VisualRect(void* ptr, void* index);
void* QAbstractItemView_VisualRegionForSelection(void* ptr, void* selection);
void QAbstractItemView_DestroyQAbstractItemView(void* ptr);
void QAbstractItemView_DestroyQAbstractItemViewDefault(void* ptr);
int QAbstractItemView___dataChanged_roles_atList(void* ptr, int i);
void QAbstractItemView___dataChanged_roles_setList(void* ptr, int i);
void* QAbstractItemView___dataChanged_roles_newList(void* ptr);
void* QAbstractItemView___selectedIndexes_atList(void* ptr, int i);
void QAbstractItemView___selectedIndexes_setList(void* ptr, void* i);
void* QAbstractItemView___selectedIndexes_newList(void* ptr);
void* QAbstractScrollArea_NewQAbstractScrollArea(void* parent);
void* QAbstractScrollArea_HorizontalScrollBar(void* ptr);
long long QAbstractScrollArea_HorizontalScrollBarPolicy(void* ptr);
void QAbstractScrollArea_SetHorizontalScrollBar(void* ptr, void* scrollBar);
void QAbstractScrollArea_SetHorizontalScrollBarPolicy(void* ptr, long long vqt);
void QAbstractScrollArea_SetVerticalScrollBar(void* ptr, void* scrollBar);
void QAbstractScrollArea_SetVerticalScrollBarPolicy(void* ptr, long long vqt);
void* QAbstractScrollArea_VerticalScrollBar(void* ptr);
long long QAbstractScrollArea_VerticalScrollBarPolicy(void* ptr);
void QAbstractScrollArea_DestroyQAbstractScrollArea(void* ptr);
void QAbstractScrollArea_DestroyQAbstractScrollAreaDefault(void* ptr);
void* QAbstractScrollArea___scrollBarWidgets_atList(void* ptr, int i);
void QAbstractScrollArea___scrollBarWidgets_setList(void* ptr, void* i);
void* QAbstractScrollArea___scrollBarWidgets_newList(void* ptr);
void* QAbstractSlider_NewQAbstractSlider(void* parent);
int QAbstractSlider_Maximum(void* ptr);
int QAbstractSlider_Minimum(void* ptr);
long long QAbstractSlider_Orientation(void* ptr);
void QAbstractSlider_SetMaximum(void* ptr, int vin);
void QAbstractSlider_SetMinimum(void* ptr, int vin);
void QAbstractSlider_SetOrientation(void* ptr, long long vqt);
void QAbstractSlider_SetOrientationDefault(void* ptr, long long vqt);
void QAbstractSlider_SetRange(void* ptr, int min, int max);
void QAbstractSlider_SetRangeDefault(void* ptr, int min, int max);
int QAbstractSlider_Value(void* ptr);
void QAbstractSlider_DestroyQAbstractSlider(void* ptr);
void QAbstractSlider_DestroyQAbstractSliderDefault(void* ptr);
void* QAction_NewQAction(void* parent);
void* QAction_NewQAction2(struct QtWidgets_PackedString text, void* parent);
void* QAction_NewQAction3(void* icon, struct QtWidgets_PackedString text, void* parent);
void QAction_Activate(void* ptr, long long event);
void QAction_ConnectChanged(void* ptr, long long t);
void QAction_DisconnectChanged(void* ptr);
void QAction_Changed(void* ptr);
void* QAction_Data(void* ptr);
char QAction_EventDefault(void* ptr, void* e);
void* QAction_Font(void* ptr);
void* QAction_Icon(void* ptr);
char QAction_IsChecked(void* ptr);
void* QAction_Menu(void* ptr);
long long QAction_Priority(void* ptr);
void QAction_SetCheckable(void* ptr, char vbo);
void QAction_SetChecked(void* ptr, char vbo);
void QAction_SetCheckedDefault(void* ptr, char vbo);
void QAction_SetData(void* ptr, void* userData);
void QAction_SetDisabled(void* ptr, char b);
void QAction_SetDisabledDefault(void* ptr, char b);
void QAction_SetEnabled(void* ptr, char vbo);
void QAction_SetEnabledDefault(void* ptr, char vbo);
void QAction_SetFont(void* ptr, void* font);
void QAction_SetIcon(void* ptr, void* icon);
void QAction_SetPriority(void* ptr, long long priority);
void QAction_SetShortcut(void* ptr, void* shortcut);
void QAction_SetText(void* ptr, struct QtWidgets_PackedString text);
void QAction_SetToolTip(void* ptr, struct QtWidgets_PackedString tip);
void* QAction_Shortcut(void* ptr);
struct QtWidgets_PackedString QAction_Text(void* ptr);
struct QtWidgets_PackedString QAction_ToolTip(void* ptr);
void QAction_Trigger(void* ptr);
void QAction_TriggerDefault(void* ptr);
void QAction_ConnectTriggered(void* ptr, long long t);
void QAction_DisconnectTriggered(void* ptr);
void QAction_Triggered(void* ptr, char checked);
void QAction_DestroyQAction(void* ptr);
void QAction_DestroyQActionDefault(void* ptr);
void* QAction___associatedGraphicsWidgets_atList(void* ptr, int i);
void QAction___associatedGraphicsWidgets_setList(void* ptr, void* i);
void* QAction___associatedGraphicsWidgets_newList(void* ptr);
void* QAction___associatedWidgets_atList(void* ptr, int i);
void QAction___associatedWidgets_setList(void* ptr, void* i);
void* QAction___associatedWidgets_newList(void* ptr);
void* QAction___setShortcuts_shortcuts_atList(void* ptr, int i);
void QAction___setShortcuts_shortcuts_setList(void* ptr, void* i);
void* QAction___setShortcuts_shortcuts_newList(void* ptr);
void* QAction___shortcuts_atList(void* ptr, int i);
void QAction___shortcuts_setList(void* ptr, void* i);
void* QAction___shortcuts_newList(void* ptr);
void* QAction___children_atList(void* ptr, int i);
void QAction___children_setList(void* ptr, void* i);
void* QAction___children_newList(void* ptr);
void* QAction___dynamicPropertyNames_atList(void* ptr, int i);
void QAction___dynamicPropertyNames_setList(void* ptr, void* i);
void* QAction___dynamicPropertyNames_newList(void* ptr);
void* QAction___findChildren_atList(void* ptr, int i);
void QAction___findChildren_setList(void* ptr, void* i);
void* QAction___findChildren_newList(void* ptr);
void* QAction___findChildren_atList3(void* ptr, int i);
void QAction___findChildren_setList3(void* ptr, void* i);
void* QAction___findChildren_newList3(void* ptr);
void QAction_ChildEventDefault(void* ptr, void* event);
void QAction_ConnectNotifyDefault(void* ptr, void* sign);
void QAction_CustomEventDefault(void* ptr, void* event);
void QAction_DeleteLaterDefault(void* ptr);
void QAction_DisconnectNotifyDefault(void* ptr, void* sign);
char QAction_EventFilterDefault(void* ptr, void* watched, void* event);
void QAction_TimerEventDefault(void* ptr, void* event);
void* QApplication_NewQApplication(int argc, char* argv);
void* QApplication_QApplication_ActiveWindow();
char QApplication_EventDefault(void* ptr, void* e);
int QApplication_QApplication_Exec();
void* QApplication_QApplication_Font();
void* QApplication_QApplication_Font2(void* widget);
void* QApplication_QApplication_Font3(char* className);
void* QApplication_QApplication_FontMetrics();
void QApplication_QApplication_SetActiveWindow(void* active);
void QApplication_QApplication_SetFont(void* font, char* className);
void QApplication_QApplication_SetStyle(void* style);
void* QApplication_QApplication_SetStyle2(struct QtWidgets_PackedString style);
void QApplication_SetStyleSheet(void* ptr, struct QtWidgets_PackedString sheet);
void QApplication_SetStyleSheetDefault(void* ptr, struct QtWidgets_PackedString sheet);
void QApplication_QApplication_SetWindowIcon(void* icon);
void* QApplication_QApplication_Style();
struct QtWidgets_PackedString QApplication_StyleSheet(void* ptr);
void* QApplication_QApplication_WindowIcon();
void QApplication_DestroyQApplication(void* ptr);
void QApplication_DestroyQApplicationDefault(void* ptr);
void* QApplication___allWidgets_atList(void* ptr, int i);
void QApplication___allWidgets_setList(void* ptr, void* i);
void* QApplication___allWidgets_newList(void* ptr);
void* QApplication___topLevelWidgets_atList(void* ptr, int i);
void QApplication___topLevelWidgets_setList(void* ptr, void* i);
void* QApplication___topLevelWidgets_newList(void* ptr);
void* QApplication___screens_atList(void* ptr, int i);
void QApplication___screens_setList(void* ptr, void* i);
void* QApplication___screens_newList(void* ptr);
void* QApplication___children_atList(void* ptr, int i);
void QApplication___children_setList(void* ptr, void* i);
void* QApplication___children_newList(void* ptr);
void* QApplication___dynamicPropertyNames_atList(void* ptr, int i);
void QApplication___dynamicPropertyNames_setList(void* ptr, void* i);
void* QApplication___dynamicPropertyNames_newList(void* ptr);
void* QApplication___findChildren_atList(void* ptr, int i);
void QApplication___findChildren_setList(void* ptr, void* i);
void* QApplication___findChildren_newList(void* ptr);
void* QApplication___findChildren_atList3(void* ptr, int i);
void QApplication___findChildren_setList3(void* ptr, void* i);
void* QApplication___findChildren_newList3(void* ptr);
void QApplication_QuitDefault(void* ptr);
void QApplication_ChildEventDefault(void* ptr, void* event);
void QApplication_ConnectNotifyDefault(void* ptr, void* sign);
void QApplication_CustomEventDefault(void* ptr, void* event);
void QApplication_DeleteLaterDefault(void* ptr);
void QApplication_DisconnectNotifyDefault(void* ptr, void* sign);
char QApplication_EventFilterDefault(void* ptr, void* watched, void* event);
void QApplication_TimerEventDefault(void* ptr, void* event);
void* QBoxLayout_NewQBoxLayout(long long dir, void* parent);
void QBoxLayout_AddItem(void* ptr, void* item);
void QBoxLayout_AddItemDefault(void* ptr, void* item);
void QBoxLayout_AddLayout(void* ptr, void* layout, int stretch);
void QBoxLayout_AddWidget(void* ptr, void* widget, int stretch, long long alignment);
int QBoxLayout_Count(void* ptr);
int QBoxLayout_CountDefault(void* ptr);
long long QBoxLayout_Direction(void* ptr);
void* QBoxLayout_ItemAt(void* ptr, int index);
void* QBoxLayout_ItemAtDefault(void* ptr, int index);
void QBoxLayout_SetStretch(void* ptr, int index, int stretch);
char QBoxLayout_SetStretchFactor(void* ptr, void* widget, int stretch);
char QBoxLayout_SetStretchFactor2(void* ptr, void* layout, int stretch);
void* QBoxLayout_SizeHint(void* ptr);
void* QBoxLayout_SizeHintDefault(void* ptr);
int QBoxLayout_Stretch(void* ptr, int index);
void* QBoxLayout_TakeAt(void* ptr, int index);
void* QBoxLayout_TakeAtDefault(void* ptr, int index);
void QBoxLayout_DestroyQBoxLayout(void* ptr);
void QBoxLayout_DestroyQBoxLayoutDefault(void* ptr);
void* QButtonGroup_NewQButtonGroup(void* parent);
void* QButtonGroup_Button(void* ptr, int id);
struct QtWidgets_PackedList QButtonGroup_Buttons(void* ptr);
int QButtonGroup_Id(void* ptr, void* button);
void QButtonGroup_DestroyQButtonGroup(void* ptr);
void QButtonGroup_DestroyQButtonGroupDefault(void* ptr);
void* QButtonGroup___buttons_atList(void* ptr, int i);
void QButtonGroup___buttons_setList(void* ptr, void* i);
void* QButtonGroup___buttons_newList(void* ptr);
void* QButtonGroup___children_atList(void* ptr, int i);
void QButtonGroup___children_setList(void* ptr, void* i);
void* QButtonGroup___children_newList(void* ptr);
void* QButtonGroup___dynamicPropertyNames_atList(void* ptr, int i);
void QButtonGroup___dynamicPropertyNames_setList(void* ptr, void* i);
void* QButtonGroup___dynamicPropertyNames_newList(void* ptr);
void* QButtonGroup___findChildren_atList(void* ptr, int i);
void QButtonGroup___findChildren_setList(void* ptr, void* i);
void* QButtonGroup___findChildren_newList(void* ptr);
void* QButtonGroup___findChildren_atList3(void* ptr, int i);
void QButtonGroup___findChildren_setList3(void* ptr, void* i);
void* QButtonGroup___findChildren_newList3(void* ptr);
void QButtonGroup_ChildEventDefault(void* ptr, void* event);
void QButtonGroup_ConnectNotifyDefault(void* ptr, void* sign);
void QButtonGroup_CustomEventDefault(void* ptr, void* event);
void QButtonGroup_DeleteLaterDefault(void* ptr);
void QButtonGroup_DisconnectNotifyDefault(void* ptr, void* sign);
char QButtonGroup_EventDefault(void* ptr, void* e);
char QButtonGroup_EventFilterDefault(void* ptr, void* watched, void* event);
void QButtonGroup_TimerEventDefault(void* ptr, void* event);
void* QColorDialog_NewQColorDialog(void* parent);
void* QColorDialog_NewQColorDialog2(void* initial, void* parent);
void QColorDialog_Done(void* ptr, int result);
void QColorDialog_DoneDefault(void* ptr, int result);
void* QColorDialog_QColorDialog_GetColor(void* initial, void* parent, struct QtWidgets_PackedString title, long long options);
void QColorDialog_Open(void* ptr, void* receiver, char* member);
void QColorDialog_DestroyQColorDialog(void* ptr);
void QColorDialog_DestroyQColorDialogDefault(void* ptr);
int QComboBox_AdjustToMinimumContentsLengthWithIcon_Type();
void* QComboBox_NewQComboBox(void* parent);
void QComboBox_ConnectActivated(void* ptr, long long t);
void QComboBox_DisconnectActivated(void* ptr);
void QComboBox_Activated(void* ptr, int index);
void QComboBox_AddItem(void* ptr, struct QtWidgets_PackedString text, void* userData);
void QComboBox_AddItem2(void* ptr, void* icon, struct QtWidgets_PackedString text, void* userData);
void QComboBox_AddItems(void* ptr, struct QtWidgets_PackedString texts);
void QComboBox_Clear(void* ptr);
void QComboBox_ClearDefault(void* ptr);
int QComboBox_Count(void* ptr);
int QComboBox_CurrentIndex(void* ptr);
struct QtWidgets_PackedString QComboBox_CurrentText(void* ptr);
void* QComboBox_LineEdit(void* ptr);
void* QComboBox_Model(void* ptr);
struct QtWidgets_PackedString QComboBox_PlaceholderText(void* ptr);
void QComboBox_SetCurrentIndex(void* ptr, int index);
void QComboBox_SetCurrentIndexDefault(void* ptr, int index);
void QComboBox_SetCurrentText(void* ptr, struct QtWidgets_PackedString text);
void QComboBox_SetCurrentTextDefault(void* ptr, struct QtWidgets_PackedString text);
void QComboBox_SetEditable(void* ptr, char editable);
void QComboBox_SetModel(void* ptr, void* model);
void QComboBox_SetPlaceholderText(void* ptr, struct QtWidgets_PackedString placeholderText);
void QComboBox_SetValidator(void* ptr, void* validator);
void* QComboBox_Validator(void* ptr);
void* QComboBox_View(void* ptr);
void QComboBox_DestroyQComboBox(void* ptr);
void QComboBox_DestroyQComboBoxDefault(void* ptr);
void* QDial_NewQDial(void* parent);
void QDial_DestroyQDial(void* ptr);
void QDial_DestroyQDialDefault(void* ptr);
void* QDialog_NewQDialog(void* parent, long long ff);
void QDialog_Accept(void* ptr);
void QDialog_AcceptDefault(void* ptr);
void QDialog_Done(void* ptr, int r);
void QDialog_DoneDefault(void* ptr, int r);
int QDialog_Exec(void* ptr);
int QDialog_ExecDefault(void* ptr);
void QDialog_ConnectFinished(void* ptr, long long t);
void QDialog_DisconnectFinished(void* ptr);
void QDialog_Finished(void* ptr, int result);
void QDialog_Open(void* ptr);
void QDialog_OpenDefault(void* ptr);
int QDialog_Result(void* ptr);
void QDialog_SetModal(void* ptr, char modal);
void QDialog_DestroyQDialog(void* ptr);
void QDialog_DestroyQDialogDefault(void* ptr);
int QDialogButtonBox_AndroidLayout_Type();
int QDirModel_FilePathRole_Type();
void* QDockWidget_NewQDockWidget(struct QtWidgets_PackedString title, void* parent, long long flags);
void* QDockWidget_NewQDockWidget2(void* parent, long long flags);
void QDockWidget_SetWidget(void* ptr, void* widget);
void* QDockWidget_Widget(void* ptr);
void QDockWidget_DestroyQDockWidget(void* ptr);
void QDockWidget_DestroyQDockWidgetDefault(void* ptr);
void* QFileDialog_NewQFileDialog(void* parent, long long flags);
void* QFileDialog_NewQFileDialog2(void* parent, struct QtWidgets_PackedString caption, struct QtWidgets_PackedString directory, struct QtWidgets_PackedString filter);
void QFileDialog_Accept(void* ptr);
void QFileDialog_AcceptDefault(void* ptr);
void* QFileDialog_Directory(void* ptr);
void QFileDialog_Done(void* ptr, int result);
void QFileDialog_DoneDefault(void* ptr, int result);
long long QFileDialog_Filter(void* ptr);
struct QtWidgets_PackedString QFileDialog_QFileDialog_GetExistingDirectory(void* parent, struct QtWidgets_PackedString caption, struct QtWidgets_PackedString dir, long long options);
struct QtWidgets_PackedString QFileDialog_QFileDialog_GetOpenFileName(void* parent, struct QtWidgets_PackedString caption, struct QtWidgets_PackedString dir, struct QtWidgets_PackedString filter, struct QtWidgets_PackedString selectedFilter, long long options);
struct QtWidgets_PackedString QFileDialog_QFileDialog_GetSaveFileName(void* parent, struct QtWidgets_PackedString caption, struct QtWidgets_PackedString dir, struct QtWidgets_PackedString filter, struct QtWidgets_PackedString selectedFilter, long long options);
void QFileDialog_Open(void* ptr, void* receiver, char* member);
void QFileDialog_SetReadOnly(void* ptr, char enabled);
void QFileDialog_DestroyQFileDialog(void* ptr);
void QFileDialog_DestroyQFileDialogDefault(void* ptr);
void* QFileDialog___getOpenFileUrls_atList(void* ptr, int i);
void QFileDialog___getOpenFileUrls_setList(void* ptr, void* i);
void* QFileDialog___getOpenFileUrls_newList(void* ptr);
void* QFileDialog___selectedUrls_atList(void* ptr, int i);
void QFileDialog___selectedUrls_setList(void* ptr, void* i);
void* QFileDialog___selectedUrls_newList(void* ptr);
void* QFileDialog___setSidebarUrls_urls_atList(void* ptr, int i);
void QFileDialog___setSidebarUrls_urls_setList(void* ptr, void* i);
void* QFileDialog___setSidebarUrls_urls_newList(void* ptr);
void* QFileDialog___sidebarUrls_atList(void* ptr, int i);
void QFileDialog___sidebarUrls_setList(void* ptr, void* i);
void* QFileDialog___sidebarUrls_newList(void* ptr);
void* QFileDialog___urlsSelected_urls_atList(void* ptr, int i);
void QFileDialog___urlsSelected_urls_setList(void* ptr, void* i);
void* QFileDialog___urlsSelected_urls_newList(void* ptr);
int QFileSystemModel_FilePathRole_Type();
int QFileSystemModel_FileNameRole_Type();
int QFileSystemModel_FilePermissions_Type();
void* QFontDialog_NewQFontDialog(void* parent);
void* QFontDialog_NewQFontDialog2(void* initial, void* parent);
void* QFontDialog_CurrentFont(void* ptr);
void QFontDialog_Done(void* ptr, int result);
void QFontDialog_DoneDefault(void* ptr, int result);
void* QFontDialog_QFontDialog_GetFont(char* ok, void* initial, void* parent, struct QtWidgets_PackedString title, long long options);
void* QFontDialog_QFontDialog_GetFont2(char* ok, void* parent);
void QFontDialog_Open(void* ptr, void* receiver, char* member);
void* QFrame_NewQFrame(void* parent, long long ff);
void QFrame_DestroyQFrame(void* ptr);
void QFrame_DestroyQFrameDefault(void* ptr);
void* QGraphicsItem_NewQGraphicsItem(void* parent);
void* QGraphicsItem_BoundingRect(void* ptr);
void QGraphicsItem_ContextMenuEvent(void* ptr, void* event);
void QGraphicsItem_ContextMenuEventDefault(void* ptr, void* event);
void* QGraphicsItem_Cursor(void* ptr);
void* QGraphicsItem_Data(void* ptr, int key);
void* QGraphicsItem_Group(void* ptr);
void QGraphicsItem_Hide(void* ptr);
void QGraphicsItem_KeyPressEvent(void* ptr, void* event);
void QGraphicsItem_KeyPressEventDefault(void* ptr, void* event);
void QGraphicsItem_KeyReleaseEvent(void* ptr, void* event);
void QGraphicsItem_KeyReleaseEventDefault(void* ptr, void* event);
void QGraphicsItem_MouseDoubleClickEvent(void* ptr, void* event);
void QGraphicsItem_MouseDoubleClickEventDefault(void* ptr, void* event);
void QGraphicsItem_MousePressEvent(void* ptr, void* event);
void QGraphicsItem_MousePressEventDefault(void* ptr, void* event);
void QGraphicsItem_MouseReleaseEvent(void* ptr, void* event);
void QGraphicsItem_MouseReleaseEventDefault(void* ptr, void* event);
void QGraphicsItem_Paint(void* ptr, void* painter, void* option, void* widget);
void* QGraphicsItem_Pos(void* ptr);
void QGraphicsItem_Scroll(void* ptr, double dx, double dy, void* rect);
void QGraphicsItem_SetActive(void* ptr, char active);
void QGraphicsItem_SetData(void* ptr, int key, void* value);
void QGraphicsItem_SetEnabled(void* ptr, char enabled);
void QGraphicsItem_SetFocus(void* ptr, long long focusReason);
void QGraphicsItem_SetPos(void* ptr, void* pos);
void QGraphicsItem_SetPos2(void* ptr, double x, double y);
void QGraphicsItem_SetToolTip(void* ptr, struct QtWidgets_PackedString toolTip);
void QGraphicsItem_Show(void* ptr);
struct QtWidgets_PackedString QGraphicsItem_ToolTip(void* ptr);
void* QGraphicsItem_Transform(void* ptr);
int QGraphicsItem_Type(void* ptr);
int QGraphicsItem_TypeDefault(void* ptr);
void QGraphicsItem_Update(void* ptr, void* rect);
void QGraphicsItem_Update2(void* ptr, double x, double y, double width, double height);
void* QGraphicsItem_Window(void* ptr);
double QGraphicsItem_X(void* ptr);
double QGraphicsItem_Y(void* ptr);
void QGraphicsItem_DestroyQGraphicsItem(void* ptr);
void QGraphicsItem_DestroyQGraphicsItemDefault(void* ptr);
void* QGraphicsItem___childItems_atList(void* ptr, int i);
void QGraphicsItem___childItems_setList(void* ptr, void* i);
void* QGraphicsItem___childItems_newList(void* ptr);
void* QGraphicsItem___children_atList(void* ptr, int i);
void QGraphicsItem___children_setList(void* ptr, void* i);
void* QGraphicsItem___children_newList(void* ptr);
void* QGraphicsItem___collidingItems_atList(void* ptr, int i);
void QGraphicsItem___collidingItems_setList(void* ptr, void* i);
void* QGraphicsItem___collidingItems_newList(void* ptr);
void* QGraphicsItem___setTransformations_transformations_atList(void* ptr, int i);
void QGraphicsItem___setTransformations_transformations_setList(void* ptr, void* i);
void* QGraphicsItem___setTransformations_transformations_newList(void* ptr);
void* QGraphicsItem___transformations_atList(void* ptr, int i);
void QGraphicsItem___transformations_setList(void* ptr, void* i);
void* QGraphicsItem___transformations_newList(void* ptr);
void* QGraphicsItemGroup_NewQGraphicsItemGroup(void* parent);
void* QGraphicsItemGroup_BoundingRect(void* ptr);
void* QGraphicsItemGroup_BoundingRectDefault(void* ptr);
void QGraphicsItemGroup_DestroyQGraphicsItemGroup(void* ptr);
void QGraphicsItemGroup_DestroyQGraphicsItemGroupDefault(void* ptr);
void QGraphicsItemGroup_Paint(void* ptr, void* painter, void* option, void* widget);
void QGraphicsItemGroup_PaintDefault(void* ptr, void* painter, void* option, void* widget);
void* QGraphicsLayout_NewQGraphicsLayout(void* parent);
void QGraphicsLayout_Activate(void* ptr);
int QGraphicsLayout_Count(void* ptr);
void QGraphicsLayout_Invalidate(void* ptr);
void QGraphicsLayout_InvalidateDefault(void* ptr);
void* QGraphicsLayout_ItemAt(void* ptr, int i);
void QGraphicsLayout_RemoveAt(void* ptr, int index);
void QGraphicsLayout_DestroyQGraphicsLayout(void* ptr);
void QGraphicsLayout_DestroyQGraphicsLayoutDefault(void* ptr);
void* QGraphicsLayout_SizeHint(void* ptr, long long which, void* constraint);
void* QGraphicsLayout_SizeHintDefault(void* ptr, long long which, void* constraint);
void* QGraphicsLayoutItem_NewQGraphicsLayoutItem(void* parent, char isLayout);
void* QGraphicsLayoutItem_Geometry(void* ptr);
void* QGraphicsLayoutItem_MaximumSize(void* ptr);
double QGraphicsLayoutItem_MaximumWidth(void* ptr);
double QGraphicsLayoutItem_MinimumHeight(void* ptr);
void* QGraphicsLayoutItem_MinimumSize(void* ptr);
double QGraphicsLayoutItem_MinimumWidth(void* ptr);
void QGraphicsLayoutItem_SetGeometry(void* ptr, void* rect);
void QGraphicsLayoutItem_SetGeometryDefault(void* ptr, void* rect);
void QGraphicsLayoutItem_SetMaximumWidth(void* ptr, double width);
void QGraphicsLayoutItem_SetMinimumSize(void* ptr, void* size);
void QGraphicsLayoutItem_SetMinimumSize2(void* ptr, double w, double h);
void QGraphicsLayoutItem_SetMinimumWidth(void* ptr, double width);
void QGraphicsLayoutItem_SetSizePolicy(void* ptr, void* policy);
void QGraphicsLayoutItem_SetSizePolicy2(void* ptr, long long hPolicy, long long vPolicy, long long controlType);
void* QGraphicsLayoutItem_SizeHint(void* ptr, long long which, void* constraint);
void* QGraphicsLayoutItem_SizePolicy(void* ptr);
void QGraphicsLayoutItem_DestroyQGraphicsLayoutItem(void* ptr);
void QGraphicsLayoutItem_DestroyQGraphicsLayoutItemDefault(void* ptr);
void* QGraphicsObject_NewQGraphicsObject(void* parent);
char QGraphicsObject_Event(void* ptr, void* ev);
char QGraphicsObject_EventDefault(void* ptr, void* ev);
void QGraphicsObject_DestroyQGraphicsObject(void* ptr);
void QGraphicsObject_DestroyQGraphicsObjectDefault(void* ptr);
void QGraphicsObject_SetEnabled(void* ptr, char enabled);
void* QGraphicsObject_Parent(void* ptr);
void* QGraphicsObject_Pos(void* ptr);
void QGraphicsObject_SetPos(void* ptr, void* pos);
double QGraphicsObject_Scale(void* ptr);
double QGraphicsObject_X(void* ptr);
double QGraphicsObject_Y(void* ptr);
void* QGraphicsObject___children_atList(void* ptr, int i);
void QGraphicsObject___children_setList(void* ptr, void* i);
void* QGraphicsObject___children_newList(void* ptr);
void* QGraphicsObject___dynamicPropertyNames_atList(void* ptr, int i);
void QGraphicsObject___dynamicPropertyNames_setList(void* ptr, void* i);
void* QGraphicsObject___dynamicPropertyNames_newList(void* ptr);
void* QGraphicsObject___findChildren_atList(void* ptr, int i);
void QGraphicsObject___findChildren_setList(void* ptr, void* i);
void* QGraphicsObject___findChildren_newList(void* ptr);
void* QGraphicsObject___findChildren_atList3(void* ptr, int i);
void QGraphicsObject___findChildren_setList3(void* ptr, void* i);
void* QGraphicsObject___findChildren_newList3(void* ptr);
void QGraphicsObject_ChildEvent(void* ptr, void* event);
void QGraphicsObject_ChildEventDefault(void* ptr, void* event);
void QGraphicsObject_ConnectNotify(void* ptr, void* sign);
void QGraphicsObject_ConnectNotifyDefault(void* ptr, void* sign);
void QGraphicsObject_CustomEvent(void* ptr, void* event);
void QGraphicsObject_CustomEventDefault(void* ptr, void* event);
void QGraphicsObject_DeleteLater(void* ptr);
void QGraphicsObject_DeleteLaterDefault(void* ptr);
void QGraphicsObject_DisconnectNotify(void* ptr, void* sign);
void QGraphicsObject_DisconnectNotifyDefault(void* ptr, void* sign);
char QGraphicsObject_EventFilter(void* ptr, void* watched, void* event);
char QGraphicsObject_EventFilterDefault(void* ptr, void* watched, void* event);
void QGraphicsObject_TimerEvent(void* ptr, void* event);
void QGraphicsObject_TimerEventDefault(void* ptr, void* event);
void* QGraphicsObject_BoundingRect(void* ptr);
void* QGraphicsObject_BoundingRectDefault(void* ptr);
void QGraphicsObject_Paint(void* ptr, void* painter, void* option, void* widget);
void QGraphicsObject_PaintDefault(void* ptr, void* painter, void* option, void* widget);
void* QGraphicsSceneContextMenuEvent_Pos(void* ptr);
void QGraphicsSceneContextMenuEvent_DestroyQGraphicsSceneContextMenuEvent(void* ptr);
void QGraphicsSceneContextMenuEvent_DestroyQGraphicsSceneContextMenuEventDefault(void* ptr);
void* QGraphicsSceneEvent_Widget(void* ptr);
void QGraphicsSceneEvent_DestroyQGraphicsSceneEvent(void* ptr);
void QGraphicsSceneEvent_DestroyQGraphicsSceneEventDefault(void* ptr);
long long QGraphicsSceneMouseEvent_Button(void* ptr);
long long QGraphicsSceneMouseEvent_Buttons(void* ptr);
void* QGraphicsSceneMouseEvent_Pos(void* ptr);
void QGraphicsSceneMouseEvent_DestroyQGraphicsSceneMouseEvent(void* ptr);
void QGraphicsSceneMouseEvent_DestroyQGraphicsSceneMouseEventDefault(void* ptr);
void* QGraphicsSceneResizeEvent_NewQGraphicsSceneResizeEvent2();
void QGraphicsSceneResizeEvent_DestroyQGraphicsSceneResizeEvent(void* ptr);
void QGraphicsSceneResizeEvent_DestroyQGraphicsSceneResizeEventDefault(void* ptr);
void* QGraphicsTransform_NewQGraphicsTransform(void* parent);
void QGraphicsTransform_ApplyTo(void* ptr, void* matrix);
void QGraphicsTransform_Update(void* ptr);
void QGraphicsTransform_UpdateDefault(void* ptr);
void QGraphicsTransform_DestroyQGraphicsTransform(void* ptr);
void QGraphicsTransform_DestroyQGraphicsTransformDefault(void* ptr);
void* QGraphicsTransform___children_atList(void* ptr, int i);
void QGraphicsTransform___children_setList(void* ptr, void* i);
void* QGraphicsTransform___children_newList(void* ptr);
void* QGraphicsTransform___dynamicPropertyNames_atList(void* ptr, int i);
void QGraphicsTransform___dynamicPropertyNames_setList(void* ptr, void* i);
void* QGraphicsTransform___dynamicPropertyNames_newList(void* ptr);
void* QGraphicsTransform___findChildren_atList(void* ptr, int i);
void QGraphicsTransform___findChildren_setList(void* ptr, void* i);
void* QGraphicsTransform___findChildren_newList(void* ptr);
void* QGraphicsTransform___findChildren_atList3(void* ptr, int i);
void QGraphicsTransform___findChildren_setList3(void* ptr, void* i);
void* QGraphicsTransform___findChildren_newList3(void* ptr);
void QGraphicsTransform_ChildEventDefault(void* ptr, void* event);
void QGraphicsTransform_ConnectNotifyDefault(void* ptr, void* sign);
void QGraphicsTransform_CustomEventDefault(void* ptr, void* event);
void QGraphicsTransform_DeleteLaterDefault(void* ptr);
void QGraphicsTransform_DisconnectNotifyDefault(void* ptr, void* sign);
char QGraphicsTransform_EventDefault(void* ptr, void* e);
char QGraphicsTransform_EventFilterDefault(void* ptr, void* watched, void* event);
void QGraphicsTransform_TimerEventDefault(void* ptr, void* event);
void* QGraphicsWidget_NewQGraphicsWidget(void* parent, long long wFlags);
struct QtWidgets_PackedList QGraphicsWidget_Actions(void* ptr);
void QGraphicsWidget_AddAction(void* ptr, void* action);
void* QGraphicsWidget_BoundingRect(void* ptr);
void* QGraphicsWidget_BoundingRectDefault(void* ptr);
char QGraphicsWidget_Close(void* ptr);
char QGraphicsWidget_CloseDefault(void* ptr);
void QGraphicsWidget_CloseEvent(void* ptr, void* event);
void QGraphicsWidget_CloseEventDefault(void* ptr, void* event);
void* QGraphicsWidget_Font(void* ptr);
void QGraphicsWidget_HideEvent(void* ptr, void* event);
void QGraphicsWidget_HideEventDefault(void* ptr, void* event);
void* QGraphicsWidget_Layout(void* ptr);
void* QGraphicsWidget_Rect(void* ptr);
void QGraphicsWidget_RemoveAction(void* ptr, void* action);
void QGraphicsWidget_Resize(void* ptr, void* size);
void QGraphicsWidget_Resize2(void* ptr, double w, double h);
void QGraphicsWidget_ResizeEvent(void* ptr, void* event);
void QGraphicsWidget_ResizeEventDefault(void* ptr, void* event);
void QGraphicsWidget_SetFont(void* ptr, void* font);
void QGraphicsWidget_SetGeometry2(void* ptr, double x, double y, double w, double h);
void QGraphicsWidget_SetLayout(void* ptr, void* layout);
void QGraphicsWidget_SetStyle(void* ptr, void* style);
void QGraphicsWidget_SetWindowTitle(void* ptr, struct QtWidgets_PackedString title);
void QGraphicsWidget_ShowEvent(void* ptr, void* event);
void QGraphicsWidget_ShowEventDefault(void* ptr, void* event);
void* QGraphicsWidget_Size(void* ptr);
void* QGraphicsWidget_SizeHint(void* ptr, long long which, void* constraint);
void* QGraphicsWidget_SizeHintDefault(void* ptr, long long which, void* constraint);
void* QGraphicsWidget_Style(void* ptr);
struct QtWidgets_PackedString QGraphicsWidget_WindowTitle(void* ptr);
void QGraphicsWidget_DestroyQGraphicsWidget(void* ptr);
void QGraphicsWidget_DestroyQGraphicsWidgetDefault(void* ptr);
void* QGraphicsWidget_Geometry(void* ptr);
void* QGraphicsWidget_MaximumSize(void* ptr);
void* QGraphicsWidget_MinimumSize(void* ptr);
void QGraphicsWidget_SetMinimumSize(void* ptr, void* minimumSize);
void* QGraphicsWidget_SizePolicy(void* ptr);
void QGraphicsWidget_SetSizePolicy(void* ptr, void* sizePolicy);
void* QGraphicsWidget___actions_atList(void* ptr, int i);
void QGraphicsWidget___actions_setList(void* ptr, void* i);
void* QGraphicsWidget___actions_newList(void* ptr);
void* QGraphicsWidget___addActions_actions_atList(void* ptr, int i);
void QGraphicsWidget___addActions_actions_setList(void* ptr, void* i);
void* QGraphicsWidget___addActions_actions_newList(void* ptr);
void* QGraphicsWidget___insertActions_actions_atList(void* ptr, int i);
void QGraphicsWidget___insertActions_actions_setList(void* ptr, void* i);
void* QGraphicsWidget___insertActions_actions_newList(void* ptr);
void* QGridLayout_NewQGridLayout(void* parent);
void* QGridLayout_NewQGridLayout2();
void QGridLayout_AddItem(void* ptr, void* item, int row, int column, int rowSpan, int columnSpan, long long alignment);
void QGridLayout_AddItem2(void* ptr, void* item);
void QGridLayout_AddItem2Default(void* ptr, void* item);
void QGridLayout_AddLayout(void* ptr, void* layout, int row, int column, long long alignment);
void QGridLayout_AddLayout2(void* ptr, void* layout, int row, int column, int rowSpan, int columnSpan, long long alignment);
void QGridLayout_AddWidget2(void* ptr, void* widget, int row, int column, long long alignment);
void QGridLayout_AddWidget3(void* ptr, void* widget, int fromRow, int fromColumn, int rowSpan, int columnSpan, long long alignment);
int QGridLayout_ColumnCount(void* ptr);
int QGridLayout_Count(void* ptr);
int QGridLayout_CountDefault(void* ptr);
void* QGridLayout_ItemAt(void* ptr, int index);
void* QGridLayout_ItemAtDefault(void* ptr, int index);
int QGridLayout_RowCount(void* ptr);
void* QGridLayout_SizeHint(void* ptr);
void* QGridLayout_SizeHintDefault(void* ptr);
void* QGridLayout_TakeAt(void* ptr, int index);
void* QGridLayout_TakeAtDefault(void* ptr, int index);
void QGridLayout_DestroyQGridLayout(void* ptr);
void QGridLayout_DestroyQGridLayoutDefault(void* ptr);
void* QHBoxLayout_NewQHBoxLayout();
void* QHBoxLayout_NewQHBoxLayout2(void* parent);
void QHBoxLayout_DestroyQHBoxLayout(void* ptr);
void QHBoxLayout_DestroyQHBoxLayoutDefault(void* ptr);
void* QHeaderView_NewQHeaderView(long long orientation, void* parent);
int QHeaderView_Count(void* ptr);
int QHeaderView_Length(void* ptr);
long long QHeaderView_Orientation(void* ptr);
void QHeaderView_SetSelection(void* ptr, void* rect, long long flags);
void QHeaderView_SetSelectionDefault(void* ptr, void* rect, long long flags);
void QHeaderView_DestroyQHeaderView(void* ptr);
void QHeaderView_DestroyQHeaderViewDefault(void* ptr);
int QHeaderView_HorizontalOffset(void* ptr);
int QHeaderView_HorizontalOffsetDefault(void* ptr);
void* QHeaderView_IndexAt(void* ptr, void* point);
void* QHeaderView_IndexAtDefault(void* ptr, void* point);
char QHeaderView_IsIndexHidden(void* ptr, void* index);
char QHeaderView_IsIndexHiddenDefault(void* ptr, void* index);
void* QHeaderView_MoveCursor(void* ptr, long long cursorAction, long long modifiers);
void* QHeaderView_MoveCursorDefault(void* ptr, long long cursorAction, long long modifiers);
void QHeaderView_ScrollTo(void* ptr, void* index, long long hint);
void QHeaderView_ScrollToDefault(void* ptr, void* index, long long hint);
int QHeaderView_VerticalOffset(void* ptr);
int QHeaderView_VerticalOffsetDefault(void* ptr);
void* QHeaderView_VisualRect(void* ptr, void* index);
void* QHeaderView_VisualRectDefault(void* ptr, void* index);
void* QHeaderView_VisualRegionForSelection(void* ptr, void* selection);
void* QHeaderView_VisualRegionForSelectionDefault(void* ptr, void* selection);
void* QInputDialog_NewQInputDialog(void* parent, long long flags);
void QInputDialog_Done(void* ptr, int result);
void QInputDialog_DoneDefault(void* ptr, int result);
struct QtWidgets_PackedString QInputDialog_QInputDialog_GetItem(void* parent, struct QtWidgets_PackedString title, struct QtWidgets_PackedString label, struct QtWidgets_PackedString items, int current, char editable, char* ok, long long flags, long long inputMethodHints);
struct QtWidgets_PackedString QInputDialog_QInputDialog_GetText(void* parent, struct QtWidgets_PackedString title, struct QtWidgets_PackedString label, long long mode, struct QtWidgets_PackedString text, char* ok, long long flags, long long inputMethodHints);
void QInputDialog_Open(void* ptr, void* receiver, char* member);
void QInputDialog_DestroyQInputDialog(void* ptr);
void QInputDialog_DestroyQInputDialogDefault(void* ptr);
void* QLabel_NewQLabel(void* parent, long long ff);
void* QLabel_NewQLabel2(struct QtWidgets_PackedString text, void* parent, long long ff);
long long QLabel_Alignment(void* ptr);
void QLabel_Clear(void* ptr);
void QLabel_ClearDefault(void* ptr);
int QLabel_Indent(void* ptr);
int QLabel_Margin(void* ptr);
struct QtWidgets_PackedString QLabel_SelectedText(void* ptr);
int QLabel_SelectionStart(void* ptr);
void QLabel_SetAlignment(void* ptr, long long vqt);
void QLabel_SetIndent(void* ptr, int vin);
void QLabel_SetPixmap(void* ptr, void* vqp);
void QLabel_SetPixmapDefault(void* ptr, void* vqp);
void QLabel_SetSelection(void* ptr, int start, int length);
void QLabel_SetText(void* ptr, struct QtWidgets_PackedString vqs);
void QLabel_SetTextDefault(void* ptr, struct QtWidgets_PackedString vqs);
struct QtWidgets_PackedString QLabel_Text(void* ptr);
void QLabel_DestroyQLabel(void* ptr);
void QLabel_DestroyQLabelDefault(void* ptr);
void* QLayout_NewQLayout(void* parent);
void* QLayout_NewQLayout2();
char QLayout_Activate(void* ptr);
void QLayout_AddItem(void* ptr, void* item);
void QLayout_AddWidget(void* ptr, void* w);
void QLayout_ChildEvent(void* ptr, void* e);
void QLayout_ChildEventDefault(void* ptr, void* e);
int QLayout_Count(void* ptr);
long long QLayout_ExpandingDirections(void* ptr);
long long QLayout_ExpandingDirectionsDefault(void* ptr);
void* QLayout_Geometry(void* ptr);
void* QLayout_GeometryDefault(void* ptr);
int QLayout_IndexOf(void* ptr, void* widget);
int QLayout_IndexOfDefault(void* ptr, void* widget);
int QLayout_IndexOf2(void* ptr, void* layoutItem);
char QLayout_IsEmpty(void* ptr);
char QLayout_IsEmptyDefault(void* ptr);
void* QLayout_ItemAt(void* ptr, int index);
void* QLayout_MaximumSize(void* ptr);
void* QLayout_MaximumSizeDefault(void* ptr);
void* QLayout_MenuBar(void* ptr);
void* QLayout_MinimumSize(void* ptr);
void* QLayout_MinimumSizeDefault(void* ptr);
char QLayout_SetAlignment(void* ptr, void* w, long long alignment);
char QLayout_SetAlignment2(void* ptr, void* l, long long alignment);
void QLayout_SetEnabled(void* ptr, char enable);
void QLayout_SetGeometry(void* ptr, void* r);
void QLayout_SetGeometryDefault(void* ptr, void* r);
void* QLayout_TakeAt(void* ptr, int index);
void QLayout_Update(void* ptr);
void* QLayout___children_atList(void* ptr, int i);
void QLayout___children_setList(void* ptr, void* i);
void* QLayout___children_newList(void* ptr);
void* QLayout___dynamicPropertyNames_atList(void* ptr, int i);
void QLayout___dynamicPropertyNames_setList(void* ptr, void* i);
void* QLayout___dynamicPropertyNames_newList(void* ptr);
void* QLayout___findChildren_atList(void* ptr, int i);
void QLayout___findChildren_setList(void* ptr, void* i);
void* QLayout___findChildren_newList(void* ptr);
void* QLayout___findChildren_atList3(void* ptr, int i);
void QLayout___findChildren_setList3(void* ptr, void* i);
void* QLayout___findChildren_newList3(void* ptr);
void QLayout_ConnectNotify(void* ptr, void* sign);
void QLayout_ConnectNotifyDefault(void* ptr, void* sign);
void QLayout_CustomEvent(void* ptr, void* event);
void QLayout_CustomEventDefault(void* ptr, void* event);
void QLayout_DeleteLater(void* ptr);
void QLayout_DeleteLaterDefault(void* ptr);
void QLayout_DisconnectNotify(void* ptr, void* sign);
void QLayout_DisconnectNotifyDefault(void* ptr, void* sign);
char QLayout_Event(void* ptr, void* e);
char QLayout_EventDefault(void* ptr, void* e);
char QLayout_EventFilter(void* ptr, void* watched, void* event);
char QLayout_EventFilterDefault(void* ptr, void* watched, void* event);
void QLayout_TimerEvent(void* ptr, void* event);
void QLayout_TimerEventDefault(void* ptr, void* event);
void* QLayout_SizeHint(void* ptr);
void* QLayout_SizeHintDefault(void* ptr);
void* QLayoutItem_NewQLayoutItem(long long alignment);
long long QLayoutItem_Alignment(void* ptr);
long long QLayoutItem_ControlTypes(void* ptr);
long long QLayoutItem_ControlTypesDefault(void* ptr);
long long QLayoutItem_ExpandingDirections(void* ptr);
void* QLayoutItem_Geometry(void* ptr);
char QLayoutItem_HasHeightForWidth(void* ptr);
char QLayoutItem_HasHeightForWidthDefault(void* ptr);
int QLayoutItem_HeightForWidth(void* ptr, int vin);
int QLayoutItem_HeightForWidthDefault(void* ptr, int vin);
void QLayoutItem_Invalidate(void* ptr);
void QLayoutItem_InvalidateDefault(void* ptr);
char QLayoutItem_IsEmpty(void* ptr);
void* QLayoutItem_Layout(void* ptr);
void* QLayoutItem_LayoutDefault(void* ptr);
void* QLayoutItem_MaximumSize(void* ptr);
int QLayoutItem_MinimumHeightForWidth(void* ptr, int w);
int QLayoutItem_MinimumHeightForWidthDefault(void* ptr, int w);
void* QLayoutItem_MinimumSize(void* ptr);
void QLayoutItem_SetAlignment(void* ptr, long long alignment);
void QLayoutItem_SetGeometry(void* ptr, void* r);
void* QLayoutItem_SizeHint(void* ptr);
void* QLayoutItem_SpacerItem(void* ptr);
void* QLayoutItem_SpacerItemDefault(void* ptr);
void* QLayoutItem_Widget(void* ptr);
void* QLayoutItem_WidgetDefault(void* ptr);
void QLayoutItem_DestroyQLayoutItem(void* ptr);
void QLayoutItem_DestroyQLayoutItemDefault(void* ptr);
void* QLineEdit_NewQLineEdit(void* parent);
void* QLineEdit_NewQLineEdit2(struct QtWidgets_PackedString contents, void* parent);
void QLineEdit_AddAction(void* ptr, void* action, long long position);
void* QLineEdit_AddAction2(void* ptr, void* icon, long long position);
long long QLineEdit_Alignment(void* ptr);
void QLineEdit_Clear(void* ptr);
void QLineEdit_ClearDefault(void* ptr);
void QLineEdit_Copy(void* ptr);
void QLineEdit_CopyDefault(void* ptr);
void* QLineEdit_CreateStandardContextMenu(void* ptr);
int QLineEdit_CursorPosition(void* ptr);
void QLineEdit_Del(void* ptr);
long long QLineEdit_EchoMode(void* ptr);
void QLineEdit_ConnectEditingFinished(void* ptr, long long t);
void QLineEdit_DisconnectEditingFinished(void* ptr);
void QLineEdit_EditingFinished(void* ptr);
void QLineEdit_End(void* ptr, char mark);
void QLineEdit_Home(void* ptr, char mark);
void QLineEdit_Insert(void* ptr, struct QtWidgets_PackedString newText);
char QLineEdit_IsModified(void* ptr);
void QLineEdit_Paste(void* ptr);
void QLineEdit_PasteDefault(void* ptr);
struct QtWidgets_PackedString QLineEdit_PlaceholderText(void* ptr);
struct QtWidgets_PackedString QLineEdit_SelectedText(void* ptr);
void QLineEdit_ConnectSelectionChanged(void* ptr, long long t);
void QLineEdit_DisconnectSelectionChanged(void* ptr);
void QLineEdit_SelectionChanged(void* ptr);
int QLineEdit_SelectionEnd(void* ptr);
int QLineEdit_SelectionStart(void* ptr);
void QLineEdit_SetAlignment(void* ptr, long long flag);
void QLineEdit_SetEchoMode(void* ptr, long long vql);
void QLineEdit_SetModified(void* ptr, char vbo);
void QLineEdit_SetPlaceholderText(void* ptr, struct QtWidgets_PackedString vqs);
void QLineEdit_SetReadOnly(void* ptr, char vbo);
void QLineEdit_SetSelection(void* ptr, int start, int length);
void QLineEdit_SetText(void* ptr, struct QtWidgets_PackedString vqs);
void QLineEdit_SetTextDefault(void* ptr, struct QtWidgets_PackedString vqs);
void QLineEdit_SetValidator(void* ptr, void* v);
struct QtWidgets_PackedString QLineEdit_Text(void* ptr);
void QLineEdit_ConnectTextChanged(void* ptr, long long t);
void QLineEdit_DisconnectTextChanged(void* ptr);
void QLineEdit_TextChanged(void* ptr, struct QtWidgets_PackedString text);
void* QLineEdit_Validator(void* ptr);
void QLineEdit_DestroyQLineEdit(void* ptr);
void QLineEdit_DestroyQLineEditDefault(void* ptr);
void* QMainWindow_NewQMainWindow(void* parent, long long flags);
void QMainWindow_AddToolBar(void* ptr, long long area, void* toolbar);
void QMainWindow_AddToolBar2(void* ptr, void* toolbar);
void* QMainWindow_AddToolBar3(void* ptr, struct QtWidgets_PackedString title);
void* QMainWindow_CentralWidget(void* ptr);
void* QMainWindow_MenuBar(void* ptr);
void QMainWindow_SetCentralWidget(void* ptr, void* widget);
void* QMainWindow_StatusBar(void* ptr);
void QMainWindow_DestroyQMainWindow(void* ptr);
void QMainWindow_DestroyQMainWindowDefault(void* ptr);
void* QMainWindow___resizeDocks_docks_atList(void* ptr, int i);
void QMainWindow___resizeDocks_docks_setList(void* ptr, void* i);
void* QMainWindow___resizeDocks_docks_newList(void* ptr);
int QMainWindow___resizeDocks_sizes_atList(void* ptr, int i);
void QMainWindow___resizeDocks_sizes_setList(void* ptr, int i);
void* QMainWindow___resizeDocks_sizes_newList(void* ptr);
void* QMainWindow___tabifiedDockWidgets_atList(void* ptr, int i);
void QMainWindow___tabifiedDockWidgets_setList(void* ptr, void* i);
void* QMainWindow___tabifiedDockWidgets_newList(void* ptr);
void* QMenu_NewQMenu(void* parent);
void* QMenu_NewQMenu2(struct QtWidgets_PackedString title, void* parent);
void* QMenu_AddAction(void* ptr, struct QtWidgets_PackedString text);
void* QMenu_AddAction2(void* ptr, void* icon, struct QtWidgets_PackedString text);
void* QMenu_AddAction3(void* ptr, struct QtWidgets_PackedString text, void* receiver, char* member, void* shortcut);
void* QMenu_AddAction4(void* ptr, void* icon, struct QtWidgets_PackedString text, void* receiver, char* member, void* shortcut);
void* QMenu_AddMenu(void* ptr, void* menu);
void* QMenu_AddMenu2(void* ptr, struct QtWidgets_PackedString title);
void* QMenu_AddMenu3(void* ptr, void* icon, struct QtWidgets_PackedString title);
void* QMenu_AddSeparator(void* ptr);
void QMenu_Clear(void* ptr);
int QMenu_ColumnCount(void* ptr);
void* QMenu_Exec(void* ptr);
void* QMenu_Exec2(void* ptr, void* p, void* action);
void* QMenu_QMenu_Exec3(void* actions, void* pos, void* at, void* parent);
void* QMenu_Icon(void* ptr);
char QMenu_IsEmpty(void* ptr);
void QMenu_Popup(void* ptr, void* p, void* atAction);
void QMenu_SetIcon(void* ptr, void* icon);
struct QtWidgets_PackedString QMenu_Title(void* ptr);
void QMenu_ConnectTriggered(void* ptr, long long t);
void QMenu_DisconnectTriggered(void* ptr);
void QMenu_Triggered(void* ptr, void* action);
void QMenu_DestroyQMenu(void* ptr);
void QMenu_DestroyQMenuDefault(void* ptr);
void* QMenu___exec_actions_atList3(void* ptr, int i);
void QMenu___exec_actions_setList3(void* ptr, void* i);
void* QMenu___exec_actions_newList3(void* ptr);
void* QMenuBar_NewQMenuBar(void* parent);
void* QMenuBar_AddAction(void* ptr, struct QtWidgets_PackedString text);
void* QMenuBar_AddAction2(void* ptr, struct QtWidgets_PackedString text, void* receiver, char* member);
void* QMenuBar_AddMenu(void* ptr, void* menu);
void* QMenuBar_AddMenu2(void* ptr, struct QtWidgets_PackedString title);
void* QMenuBar_AddMenu3(void* ptr, void* icon, struct QtWidgets_PackedString title);
void* QMenuBar_AddSeparator(void* ptr);
void QMenuBar_Clear(void* ptr);
void QMenuBar_ConnectTriggered(void* ptr, long long t);
void QMenuBar_DisconnectTriggered(void* ptr);
void QMenuBar_Triggered(void* ptr, void* action);
void QMenuBar_DestroyQMenuBar(void* ptr);
void QMenuBar_DestroyQMenuBarDefault(void* ptr);
int QMessageBox_ButtonMask_Type();
void* QMessageBox_NewQMessageBox(void* parent);
void* QMessageBox_NewQMessageBox2(long long icon, struct QtWidgets_PackedString title, struct QtWidgets_PackedString text, long long buttons, void* parent, long long ff);
void QMessageBox_QMessageBox_About(void* parent, struct QtWidgets_PackedString title, struct QtWidgets_PackedString text);
void* QMessageBox_Button(void* ptr, long long which);
struct QtWidgets_PackedList QMessageBox_Buttons(void* ptr);
long long QMessageBox_Icon(void* ptr);
long long QMessageBox_QMessageBox_Information(void* parent, struct QtWidgets_PackedString title, struct QtWidgets_PackedString text, long long buttons, long long defaultButton);
void QMessageBox_Open(void* ptr, void* receiver, char* member);
long long QMessageBox_QMessageBox_Question(void* parent, struct QtWidgets_PackedString title, struct QtWidgets_PackedString text, long long buttons, long long defaultButton);
void QMessageBox_SetIcon(void* ptr, long long vqm);
void QMessageBox_SetStandardButtons(void* ptr, long long buttons);
void QMessageBox_SetText(void* ptr, struct QtWidgets_PackedString text);
void QMessageBox_SetWindowTitle(void* ptr, struct QtWidgets_PackedString title);
long long QMessageBox_StandardButton(void* ptr, void* button);
long long QMessageBox_StandardButtons(void* ptr);
struct QtWidgets_PackedString QMessageBox_Text(void* ptr);
long long QMessageBox_QMessageBox_Warning(void* parent, struct QtWidgets_PackedString title, struct QtWidgets_PackedString text, long long buttons, long long defaultButton);
void QMessageBox_DestroyQMessageBox(void* ptr);
void QMessageBox_DestroyQMessageBoxDefault(void* ptr);
void* QMessageBox___buttons_atList(void* ptr, int i);
void QMessageBox___buttons_setList(void* ptr, void* i);
void* QMessageBox___buttons_newList(void* ptr);
void* QPushButton_NewQPushButton(void* parent);
void* QPushButton_NewQPushButton2(struct QtWidgets_PackedString text, void* parent);
void* QPushButton_NewQPushButton3(void* icon, struct QtWidgets_PackedString text, void* parent);
void* QPushButton_Menu(void* ptr);
void QPushButton_DestroyQPushButton(void* ptr);
void QPushButton_DestroyQPushButtonDefault(void* ptr);
void QPushButton_PaintEvent(void* ptr, void* e);
void QPushButton_PaintEventDefault(void* ptr, void* e);
void* QScrollArea_NewQScrollArea(void* parent);
long long QScrollArea_Alignment(void* ptr);
void QScrollArea_SetAlignment(void* ptr, long long vqt);
void QScrollArea_SetWidget(void* ptr, void* widget);
void* QScrollArea_Widget(void* ptr);
void QScrollArea_DestroyQScrollArea(void* ptr);
void QScrollArea_DestroyQScrollAreaDefault(void* ptr);
void* QScrollBar_NewQScrollBar(void* parent);
void* QScrollBar_NewQScrollBar2(long long orientation, void* parent);
void QScrollBar_DestroyQScrollBar(void* ptr);
void QScrollBar_DestroyQScrollBarDefault(void* ptr);
void* QSizePolicy_NewQSizePolicy();
void* QSizePolicy_NewQSizePolicy2(long long horizontal, long long vertical, long long ty);
long long QSizePolicy_ControlType(void* ptr);
long long QSizePolicy_ExpandingDirections(void* ptr);
char QSizePolicy_HasHeightForWidth(void* ptr);
void* QSpacerItem_NewQSpacerItem(int w, int h, long long hPolicy, long long vPolicy);
long long QSpacerItem_ExpandingDirections(void* ptr);
long long QSpacerItem_ExpandingDirectionsDefault(void* ptr);
void* QSpacerItem_Geometry(void* ptr);
void* QSpacerItem_GeometryDefault(void* ptr);
char QSpacerItem_IsEmpty(void* ptr);
char QSpacerItem_IsEmptyDefault(void* ptr);
void* QSpacerItem_MaximumSize(void* ptr);
void* QSpacerItem_MaximumSizeDefault(void* ptr);
void* QSpacerItem_MinimumSize(void* ptr);
void* QSpacerItem_MinimumSizeDefault(void* ptr);
void QSpacerItem_SetGeometry(void* ptr, void* r);
void QSpacerItem_SetGeometryDefault(void* ptr, void* r);
void* QSpacerItem_SizeHint(void* ptr);
void* QSpacerItem_SizeHintDefault(void* ptr);
void* QSpacerItem_SizePolicy(void* ptr);
void QSpacerItem_DestroyQSpacerItem(void* ptr);
void QSpacerItem_DestroyQSpacerItemDefault(void* ptr);
void* QSplitter_NewQSplitter(void* parent);
void* QSplitter_NewQSplitter2(long long orientation, void* parent);
void QSplitter_AddWidget(void* ptr, void* widget);
int QSplitter_Count(void* ptr);
int QSplitter_IndexOf(void* ptr, void* widget);
long long QSplitter_Orientation(void* ptr);
void QSplitter_Refresh(void* ptr);
void QSplitter_SetOrientation(void* ptr, long long vqt);
void QSplitter_SetStretchFactor(void* ptr, int index, int stretch);
void* QSplitter_Widget(void* ptr, int index);
void QSplitter_DestroyQSplitter(void* ptr);
void QSplitter_DestroyQSplitterDefault(void* ptr);
int QSplitter___setSizes_list_atList(void* ptr, int i);
void QSplitter___setSizes_list_setList(void* ptr, int i);
void* QSplitter___setSizes_list_newList(void* ptr);
int QSplitter___sizes_atList(void* ptr, int i);
void QSplitter___sizes_setList(void* ptr, int i);
void* QSplitter___sizes_newList(void* ptr);
void* QStatusBar_NewQStatusBar(void* parent);
void QStatusBar_AddWidget(void* ptr, void* widget, int stretch);
void QStatusBar_ShowMessage(void* ptr, struct QtWidgets_PackedString message, int timeout);
void QStatusBar_ShowMessageDefault(void* ptr, struct QtWidgets_PackedString message, int timeout);
void QStatusBar_DestroyQStatusBar(void* ptr);
void QStatusBar_DestroyQStatusBarDefault(void* ptr);
int QStyle_PM_ToolBarIconSize_Type();
int QStyle_SE_LabelLayoutItem_Type();
void* QStyle_NewQStyle2();
void QStyle_DrawComplexControl(void* ptr, long long control, void* option, void* painter, void* widget);
void QStyle_DrawControl(void* ptr, long long element, void* option, void* painter, void* widget);
void QStyle_DrawPrimitive(void* ptr, long long element, void* option, void* painter, void* widget);
void* QStyle_GeneratedIconPixmap(void* ptr, long long iconMode, void* pixmap, void* option);
long long QStyle_HitTestComplexControl(void* ptr, long long control, void* option, void* position, void* widget);
int QStyle_LayoutSpacing(void* ptr, long long control1, long long control2, long long orientation, void* option, void* widget);
int QStyle_PixelMetric(void* ptr, long long metric, void* option, void* widget);
void* QStyle_SizeFromContents(void* ptr, long long ty, void* option, void* contentsSize, void* widget);
void* QStyle_StandardIcon(void* ptr, long long standardIcon, void* option, void* widget);
int QStyle_StyleHint(void* ptr, long long hint, void* option, void* widget, void* returnData);
void* QStyle_SubControlRect(void* ptr, long long control, void* option, long long subControl, void* widget);
void* QStyle_SubElementRect(void* ptr, long long element, void* option, void* widget);
void QStyle_DestroyQStyle(void* ptr);
void QStyle_DestroyQStyleDefault(void* ptr);
void* QStyle_StandardPixmap(void* ptr, long long standardIcon, void* option, void* widget);
void* QStyle___children_atList(void* ptr, int i);
void QStyle___children_setList(void* ptr, void* i);
void* QStyle___children_newList(void* ptr);
void* QStyle___dynamicPropertyNames_atList(void* ptr, int i);
void QStyle___dynamicPropertyNames_setList(void* ptr, void* i);
void* QStyle___dynamicPropertyNames_newList(void* ptr);
void* QStyle___findChildren_atList(void* ptr, int i);
void QStyle___findChildren_setList(void* ptr, void* i);
void* QStyle___findChildren_newList(void* ptr);
void* QStyle___findChildren_atList3(void* ptr, int i);
void QStyle___findChildren_setList3(void* ptr, void* i);
void* QStyle___findChildren_newList3(void* ptr);
void QStyle_ChildEventDefault(void* ptr, void* event);
void QStyle_ConnectNotifyDefault(void* ptr, void* sign);
void QStyle_CustomEventDefault(void* ptr, void* event);
void QStyle_DeleteLaterDefault(void* ptr);
void QStyle_DisconnectNotifyDefault(void* ptr, void* sign);
char QStyle_EventDefault(void* ptr, void* e);
char QStyle_EventFilterDefault(void* ptr, void* watched, void* event);
void QStyle_TimerEventDefault(void* ptr, void* event);
void* QStyleHintReturn_NewQStyleHintReturn(int version, int ty);
int QStyleHintReturn_Type(void* ptr);
int QStyleHintReturn_Version(void* ptr);
void* QStyleOption_NewQStyleOption(int version, int ty);
void* QStyleOption_NewQStyleOption2(void* other);
void QStyleOption_DestroyQStyleOption(void* ptr);
long long QStyleOption_Direction(void* ptr);
void* QStyleOption_FontMetrics(void* ptr);
void* QStyleOption_Rect(void* ptr);
int QStyleOption_Type(void* ptr);
int QStyleOption_Version(void* ptr);
void* QStyleOptionComplex_NewQStyleOptionComplex(int version, int ty);
void* QStyleOptionComplex_NewQStyleOptionComplex2(void* other);
void* QStyleOptionGraphicsItem_NewQStyleOptionGraphicsItem();
void* QStyleOptionGraphicsItem_NewQStyleOptionGraphicsItem2(void* other);
void* QTextEdit_NewQTextEdit(void* parent);
void* QTextEdit_NewQTextEdit2(struct QtWidgets_PackedString text, void* parent);
long long QTextEdit_Alignment(void* ptr);
void QTextEdit_Append(void* ptr, struct QtWidgets_PackedString text);
void QTextEdit_AppendDefault(void* ptr, struct QtWidgets_PackedString text);
void QTextEdit_Clear(void* ptr);
void QTextEdit_ClearDefault(void* ptr);
void QTextEdit_Copy(void* ptr);
void QTextEdit_CopyDefault(void* ptr);
void* QTextEdit_CreateStandardContextMenu(void* ptr);
void* QTextEdit_CreateStandardContextMenu2(void* ptr, void* position);
void* QTextEdit_CurrentCharFormat(void* ptr);
void* QTextEdit_CurrentFont(void* ptr);
void* QTextEdit_Document(void* ptr);
char QTextEdit_Find(void* ptr, struct QtWidgets_PackedString exp, long long options);
char QTextEdit_Find2(void* ptr, void* exp, long long options);
char QTextEdit_Find3(void* ptr, void* exp, long long options);
char QTextEdit_FontItalic(void* ptr);
double QTextEdit_FontPointSize(void* ptr);
char QTextEdit_FontUnderline(void* ptr);
int QTextEdit_FontWeight(void* ptr);
void QTextEdit_InsertPlainText(void* ptr, struct QtWidgets_PackedString text);
void QTextEdit_InsertPlainTextDefault(void* ptr, struct QtWidgets_PackedString text);
void QTextEdit_MergeCurrentCharFormat(void* ptr, void* modifier);
void QTextEdit_Paste(void* ptr);
void QTextEdit_PasteDefault(void* ptr);
struct QtWidgets_PackedString QTextEdit_PlaceholderText(void* ptr);
void QTextEdit_Print(void* ptr, void* printer);
void QTextEdit_ConnectSelectionChanged(void* ptr, long long t);
void QTextEdit_DisconnectSelectionChanged(void* ptr);
void QTextEdit_SelectionChanged(void* ptr);
void QTextEdit_SetAlignment(void* ptr, long long a);
void QTextEdit_SetAlignmentDefault(void* ptr, long long a);
void QTextEdit_SetCurrentCharFormat(void* ptr, void* format);
void QTextEdit_SetFontItalic(void* ptr, char italic);
void QTextEdit_SetFontItalicDefault(void* ptr, char italic);
void QTextEdit_SetFontPointSize(void* ptr, double s);
void QTextEdit_SetFontPointSizeDefault(void* ptr, double s);
void QTextEdit_SetFontUnderline(void* ptr, char underline);
void QTextEdit_SetFontUnderlineDefault(void* ptr, char underline);
void QTextEdit_SetFontWeight(void* ptr, int weight);
void QTextEdit_SetFontWeightDefault(void* ptr, int weight);
void QTextEdit_SetHtml(void* ptr, struct QtWidgets_PackedString text);
void QTextEdit_SetHtmlDefault(void* ptr, struct QtWidgets_PackedString text);
void QTextEdit_SetPlaceholderText(void* ptr, struct QtWidgets_PackedString placeholderText);
void QTextEdit_SetReadOnly(void* ptr, char ro);
void QTextEdit_SetTabChangesFocus(void* ptr, char b);
void QTextEdit_SetTabStopWidth(void* ptr, int width);
void QTextEdit_SetText(void* ptr, struct QtWidgets_PackedString text);
void QTextEdit_SetTextDefault(void* ptr, struct QtWidgets_PackedString text);
void QTextEdit_SetTextCursor(void* ptr, void* cursor);
char QTextEdit_TabChangesFocus(void* ptr);
int QTextEdit_TabStopWidth(void* ptr);
void QTextEdit_ConnectTextChanged(void* ptr, long long t);
void QTextEdit_DisconnectTextChanged(void* ptr);
void QTextEdit_TextChanged(void* ptr);
void* QTextEdit_TextColor(void* ptr);
void* QTextEdit_TextCursor(void* ptr);
struct QtWidgets_PackedString QTextEdit_ToHtml(void* ptr);
struct QtWidgets_PackedString QTextEdit_ToPlainText(void* ptr);
void QTextEdit_DestroyQTextEdit(void* ptr);
void QTextEdit_DestroyQTextEditDefault(void* ptr);
void* QToolBar_NewQToolBar(struct QtWidgets_PackedString title, void* parent);
void* QToolBar_NewQToolBar2(void* parent);
void* QToolBar_AddAction(void* ptr, struct QtWidgets_PackedString text);
void* QToolBar_AddAction2(void* ptr, void* icon, struct QtWidgets_PackedString text);
void* QToolBar_AddAction3(void* ptr, struct QtWidgets_PackedString text, void* receiver, char* member);
void* QToolBar_AddAction4(void* ptr, void* icon, struct QtWidgets_PackedString text, void* receiver, char* member);
void* QToolBar_AddSeparator(void* ptr);
void* QToolBar_AddWidget(void* ptr, void* widget);
void QToolBar_Clear(void* ptr);
long long QToolBar_Orientation(void* ptr);
void QToolBar_SetOrientation(void* ptr, long long orientation);
void QToolBar_DestroyQToolBar(void* ptr);
void QToolBar_DestroyQToolBarDefault(void* ptr);
void* QTreeView_NewQTreeView(void* parent);
void QTreeView_Collapse(void* ptr, void* index);
void QTreeView_CollapseDefault(void* ptr, void* index);
void QTreeView_ConnectCollapsed(void* ptr, long long t);
void QTreeView_DisconnectCollapsed(void* ptr);
void QTreeView_Collapsed(void* ptr, void* index);
void QTreeView_Expand(void* ptr, void* index);
void QTreeView_ExpandDefault(void* ptr, void* index);
void QTreeView_ConnectExpanded(void* ptr, long long t);
void QTreeView_DisconnectExpanded(void* ptr);
void QTreeView_Expanded(void* ptr, void* index);
void* QTreeView_Header(void* ptr);
void* QTreeView_IndexAt(void* ptr, void* point);
void* QTreeView_IndexAtDefault(void* ptr, void* point);
char QTreeView_IsExpanded(void* ptr, void* index);
void QTreeView_ResizeColumnToContents(void* ptr, int column);
void QTreeView_ResizeColumnToContentsDefault(void* ptr, int column);
void QTreeView_SelectionChanged(void* ptr, void* selected, void* deselected);
void QTreeView_SelectionChangedDefault(void* ptr, void* selected, void* deselected);
void QTreeView_SetSelection(void* ptr, void* rect, long long command);
void QTreeView_SetSelectionDefault(void* ptr, void* rect, long long command);
void QTreeView_DestroyQTreeView(void* ptr);
void QTreeView_DestroyQTreeViewDefault(void* ptr);
int QTreeView_HorizontalOffset(void* ptr);
int QTreeView_HorizontalOffsetDefault(void* ptr);
char QTreeView_IsIndexHidden(void* ptr, void* index);
char QTreeView_IsIndexHiddenDefault(void* ptr, void* index);
void* QTreeView_MoveCursor(void* ptr, long long cursorAction, long long modifiers);
void* QTreeView_MoveCursorDefault(void* ptr, long long cursorAction, long long modifiers);
void QTreeView_ScrollTo(void* ptr, void* index, long long hint);
void QTreeView_ScrollToDefault(void* ptr, void* index, long long hint);
int QTreeView_VerticalOffset(void* ptr);
int QTreeView_VerticalOffsetDefault(void* ptr);
void* QTreeView_VisualRect(void* ptr, void* index);
void* QTreeView_VisualRectDefault(void* ptr, void* index);
void* QTreeView_VisualRegionForSelection(void* ptr, void* selection);
void* QTreeView_VisualRegionForSelectionDefault(void* ptr, void* selection);
void* QVBoxLayout_NewQVBoxLayout();
void* QVBoxLayout_NewQVBoxLayout2(void* parent);
void QVBoxLayout_DestroyQVBoxLayout(void* ptr);
void QVBoxLayout_DestroyQVBoxLayoutDefault(void* ptr);
void* QWidget_NewQWidget(void* parent, long long ff);
struct QtWidgets_PackedString QWidget_AccessibleDescription(void* ptr);
struct QtWidgets_PackedList QWidget_Actions(void* ptr);
void QWidget_ActivateWindow(void* ptr);
void QWidget_AddAction(void* ptr, void* action);
char QWidget_Close(void* ptr);
char QWidget_CloseDefault(void* ptr);
void QWidget_CloseEvent(void* ptr, void* event);
void QWidget_CloseEventDefault(void* ptr, void* event);
void QWidget_ContextMenuEvent(void* ptr, void* event);
void QWidget_ContextMenuEventDefault(void* ptr, void* event);
void QWidget_Create(void* ptr, uintptr_t window, char initializeWindow, char destroyOldWindow);
void* QWidget_Cursor(void* ptr);
void QWidget_Destroy(void* ptr, char destroyWindow, char destroySubWindows);
char QWidget_Event(void* ptr, void* event);
char QWidget_EventDefault(void* ptr, void* event);
void* QWidget_QWidget_Find(uintptr_t id);
void* QWidget_Font(void* ptr);
void* QWidget_FontMetrics(void* ptr);
void* QWidget_Geometry(void* ptr);
char QWidget_HasHeightForWidth(void* ptr);
char QWidget_HasHeightForWidthDefault(void* ptr);
int QWidget_Height(void* ptr);
int QWidget_HeightForWidth(void* ptr, int w);
int QWidget_HeightForWidthDefault(void* ptr, int w);
void QWidget_Hide(void* ptr);
void QWidget_HideDefault(void* ptr);
void QWidget_HideEvent(void* ptr, void* event);
void QWidget_HideEventDefault(void* ptr, void* event);
void QWidget_KeyPressEvent(void* ptr, void* event);
void QWidget_KeyPressEventDefault(void* ptr, void* event);
void QWidget_KeyReleaseEvent(void* ptr, void* event);
void QWidget_KeyReleaseEventDefault(void* ptr, void* event);
void* QWidget_Layout(void* ptr);
void QWidget_Lower(void* ptr);
void QWidget_LowerDefault(void* ptr);
void* QWidget_MaximumSize(void* ptr);
int QWidget_MaximumWidth(void* ptr);
int QWidget_Metric(void* ptr, long long m);
int QWidget_MetricDefault(void* ptr, long long m);
int QWidget_MinimumHeight(void* ptr);
void* QWidget_MinimumSize(void* ptr);
int QWidget_MinimumWidth(void* ptr);
void QWidget_MouseDoubleClickEvent(void* ptr, void* event);
void QWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QWidget_MousePressEvent(void* ptr, void* event);
void QWidget_MousePressEventDefault(void* ptr, void* event);
void QWidget_MouseReleaseEvent(void* ptr, void* event);
void QWidget_MouseReleaseEventDefault(void* ptr, void* event);
void QWidget_Move(void* ptr, void* vqp);
void QWidget_Move2(void* ptr, int x, int y);
void* QWidget_Pos(void* ptr);
void* QWidget_Rect(void* ptr);
void QWidget_RemoveAction(void* ptr, void* action);
void QWidget_Resize(void* ptr, void* vqs);
void QWidget_Resize2(void* ptr, int w, int h);
void QWidget_ResizeEvent(void* ptr, void* event);
void QWidget_ResizeEventDefault(void* ptr, void* event);
void QWidget_Scroll(void* ptr, int dx, int dy);
void QWidget_Scroll2(void* ptr, int dx, int dy, void* r);
void QWidget_SetAccessibleDescription(void* ptr, struct QtWidgets_PackedString description);
void QWidget_SetDisabled(void* ptr, char disable);
void QWidget_SetDisabledDefault(void* ptr, char disable);
void QWidget_SetEnabled(void* ptr, char vbo);
void QWidget_SetEnabledDefault(void* ptr, char vbo);
void QWidget_SetFixedSize(void* ptr, void* s);
void QWidget_SetFixedSize2(void* ptr, int w, int h);
void QWidget_SetFixedWidth(void* ptr, int w);
void QWidget_SetFocus(void* ptr, long long reason);
void QWidget_SetFocus2(void* ptr);
void QWidget_SetFocus2Default(void* ptr);
void QWidget_SetFont(void* ptr, void* vqf);
void QWidget_SetGeometry(void* ptr, void* vqr);
void QWidget_SetGeometry2(void* ptr, int x, int y, int w, int h);
void QWidget_SetLayout(void* ptr, void* layout);
void QWidget_SetMaximumWidth(void* ptr, int maxw);
void QWidget_SetMinimumSize(void* ptr, void* vqs);
void QWidget_SetMinimumSize2(void* ptr, int minw, int minh);
void QWidget_SetMinimumWidth(void* ptr, int minw);
void QWidget_SetSizePolicy(void* ptr, void* vqs);
void QWidget_SetSizePolicy2(void* ptr, long long horizontal, long long vertical);
void QWidget_SetStyle(void* ptr, void* style);
void QWidget_SetStyleSheet(void* ptr, struct QtWidgets_PackedString styleSheet);
void QWidget_SetStyleSheetDefault(void* ptr, struct QtWidgets_PackedString styleSheet);
void QWidget_SetToolTip(void* ptr, struct QtWidgets_PackedString vqs);
void QWidget_SetWindowIcon(void* ptr, void* icon);
void QWidget_SetWindowTitle(void* ptr, struct QtWidgets_PackedString vqs);
void QWidget_SetWindowTitleDefault(void* ptr, struct QtWidgets_PackedString vqs);
void QWidget_Show(void* ptr);
void QWidget_ShowDefault(void* ptr);
void QWidget_ShowEvent(void* ptr, void* event);
void QWidget_ShowEventDefault(void* ptr, void* event);
void QWidget_ShowMaximized(void* ptr);
void QWidget_ShowMaximizedDefault(void* ptr);
void* QWidget_Size(void* ptr);
void* QWidget_SizeHint(void* ptr);
void* QWidget_SizeHintDefault(void* ptr);
void* QWidget_SizePolicy(void* ptr);
void* QWidget_Style(void* ptr);
struct QtWidgets_PackedString QWidget_StyleSheet(void* ptr);
struct QtWidgets_PackedString QWidget_ToolTip(void* ptr);
void QWidget_Update(void* ptr);
void QWidget_UpdateDefault(void* ptr);
void QWidget_Update2(void* ptr, int x, int y, int w, int h);
void QWidget_Update3(void* ptr, void* rect);
void QWidget_Update4(void* ptr, void* rgn);
int QWidget_Width(void* ptr);
void* QWidget_Window(void* ptr);
void* QWidget_WindowIcon(void* ptr);
struct QtWidgets_PackedString QWidget_WindowTitle(void* ptr);
int QWidget_X(void* ptr);
int QWidget_Y(void* ptr);
void QWidget_DestroyQWidget(void* ptr);
void QWidget_DestroyQWidgetDefault(void* ptr);
void* QWidget___actions_atList(void* ptr, int i);
void QWidget___actions_setList(void* ptr, void* i);
void* QWidget___actions_newList(void* ptr);
void* QWidget___addActions_actions_atList(void* ptr, int i);
void QWidget___addActions_actions_setList(void* ptr, void* i);
void* QWidget___addActions_actions_newList(void* ptr);
void* QWidget___insertActions_actions_atList(void* ptr, int i);
void QWidget___insertActions_actions_setList(void* ptr, void* i);
void* QWidget___insertActions_actions_newList(void* ptr);
void* QWidget___children_atList(void* ptr, int i);
void QWidget___children_setList(void* ptr, void* i);
void* QWidget___children_newList(void* ptr);
void* QWidget___dynamicPropertyNames_atList(void* ptr, int i);
void QWidget___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWidget___dynamicPropertyNames_newList(void* ptr);
void* QWidget___findChildren_atList(void* ptr, int i);
void QWidget___findChildren_setList(void* ptr, void* i);
void* QWidget___findChildren_newList(void* ptr);
void* QWidget___findChildren_atList3(void* ptr, int i);
void QWidget___findChildren_setList3(void* ptr, void* i);
void* QWidget___findChildren_newList3(void* ptr);
void QWidget_ChildEvent(void* ptr, void* event);
void QWidget_ChildEventDefault(void* ptr, void* event);
void QWidget_ConnectNotify(void* ptr, void* sign);
void QWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QWidget_CustomEvent(void* ptr, void* event);
void QWidget_CustomEventDefault(void* ptr, void* event);
void QWidget_DeleteLater(void* ptr);
void QWidget_DeleteLaterDefault(void* ptr);
void QWidget_DisconnectNotify(void* ptr, void* sign);
void QWidget_DisconnectNotifyDefault(void* ptr, void* sign);
char QWidget_EventFilter(void* ptr, void* watched, void* event);
char QWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void QWidget_TimerEvent(void* ptr, void* event);
void QWidget_TimerEventDefault(void* ptr, void* event);
void* QWidget_PaintEngine(void* ptr);
void* QWidget_PaintEngineDefault(void* ptr);

#ifdef __cplusplus
}
#endif

#endif